In [3]:
import pandas as pd
import json

# Caminho para seu arquivo
file_path = 'similarity_results.jsonl'

# Carrega cada linha do arquivo como um dicionário
data = []
with open(file_path, 'r', encoding='utf-8') as f:
    for line in f:
        item = json.loads(line)
        # Extrai campos desejados
        row = {
            'similarity_result': item['similarity_result'],
            'diagnosed_name': item['diagnosed']['name'],
            'diagnosed_given': item['diagnosed']['given'],
            'diagnosed_then': item['diagnosed']['then'],
            'candidate_name': item['candidate']['name'],
            'candidate_given': item['candidate']['given'],
            'candidate_then': item['candidate']['then'],
            'elapsed_time': item['elapsed_time'],
            'config': item['config'],
        }
        data.append(row)

# Cria o DataFrame
df = pd.DataFrame(data)

# Exemplo: mostra as primeiras linhas
df

,similarity_result,diagnosed_name,diagnosed_given,diagnosed_then,candidate_name,candidate_given,candidate_then,elapsed_time,config
0,1.000000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.109511,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '..."
1,0.875000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_given_low,p1 >= 20 AND p2 >= 20 AND p3 >= 20 AND p4 >= 2...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.144333,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '..."
2,0.800000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_given_high,p1 >= 80 AND p2 >= 80 AND p3 >= 80 AND p4 >= 8...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.112845,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '..."
3,0.875000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_then_low,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 20 AND p7 >= 20 AND p8 >= 20 AND p9 >= 2...,0.131997,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '..."
4,0.800000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_then_high,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 80 AND p7 >= 80 AND p8 >= 80 AND p9 >= 8...,0.131111,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '..."
5,0.750000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_given_then_low,p1 >= 20 AND p2 >= 20 AND p3 >= 20 AND p4 >= 2...,p6 >= 20 AND p7 >= 20 AND p8 >= 20 AND p9 >= 2...,0.118806,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '..."
6,0.600000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_given_then_high,p1 >= 80 AND p2 >= 80 AND p3 >= 80 AND p4 >= 8...,p6 >= 80 AND p7 >= 80 AND p8 >= 80 AND p9 >= 8...,0.122367,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '..."
7,0.833333,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_when_high,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.095124,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '..."
8,1.000000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.135476,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '..."
9,0.775000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_given_low,p1 >= 20 AND p2 >= 20 AND p3 >= 20 AND p4 >= 2...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.118131,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '..."
10,0.640000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_given_high,p1 >= 80 AND p2 >= 80 AND p3 >= 80 AND p4 >= 8...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.093349,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '..."
11,0.925000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_then_low,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 20 AND p7 >= 20 AND p8 >= 20 AND p9 >= 2...,0.084119,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '..."
12,0.880000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_then_high,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 80 AND p7 >= 80 AND p8 >= 80 AND p9 >= 8...,0.086661,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '..."
13,0.700000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_given_then_low,p1 >= 20 AND p2 >= 20 AND p3 >= 20 AND p4 >= 2...,p6 >= 20 AND p7 >= 20 AND p8 >= 20 AND p9 >= 2...,0.109106,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '..."
14,0.520000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_given_then_high,p1 >= 80 AND p2 >= 80 AND p3 >= 80 AND p4 >= 8...,p6 >= 80 AND p7 >= 80 AND p8 >= 80 AND p9 >= 8...,0.099040,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '..."
15,0.900000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_when_high,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.095989,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '..."
16,1.000000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.108254,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '..."
17,0.925000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_given_low,p1 >= 20 AND p2 >= 20 AND p3 >= 20 AND p4 >= 2...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.098002,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '..."
18,0.880000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_given_high,p1 >= 80 AND p2 >= 80 AND p3 >= 80 AND p4 >= 8...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.103238,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '..."
19,0.775000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_then_low,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 20 AND p7 >= 20 AND p8 >= 20 AND p9 >= 2...,0.110659,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '..."
20,0.640000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_then_high,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 80 AND p7 >= 80 AND p8 >= 80 AND p9 >= 8...,0.087396,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '..."
21,0.700000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_given_then_low,p1 >= 20 AND p2 >= 20 AND p3 >= 20 AND p4 >= 2...,p6 >= 20 AND p7 >= 20 AND p8 >= 20 AND p9 >= 2...,0.097267,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '..."
22,0.520000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_given_then_high,p1 >= 80 AND p2 >= 80 AND p3 >= 80 AND p4 >= 8...,p6 >= 80 AND p7 >= 80 AND p8 >= 80 AND p9 >= 8...,0.099623,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '..."
23,0.900000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_when_high,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.092654,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '..."
24,1.000000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.106620,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '..."
25,0.925000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_given_low,p1 >= 20 AND p2 >= 20 AND p3 >= 20 AND p4 >= 2...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.103085,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '..."
26,0.880000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_given_high,p1 >= 80 AND p2 >= 80 AND p3 >= 80 AND p4 >= 8...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.100841,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '..."
27,0.925000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_then_low,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 20 AND p7 >= 20 AND p8 >= 20 AND p9 >= 2...,0.096083,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '..."
28,0.880000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_then_high,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 80 AND p7 >= 80 AND p8 >= 80 AND p9 >= 8...,0.090864,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '..."
29,0.850000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_given_then_low,p1 >= 20 AND p2 >= 20 AND p3 >= 20 AND p4 >= 2...,p6 >= 20 AND p7 >= 20 AND p8 >= 20 AND p9 >= 2...,0.119998,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '..."
30,0.760000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_given_then_high,p1 >= 80 AND p2 >= 80 AND p3 >= 80 AND p4 >= 8...,p6 >= 80 AND p7 >= 80 AND p8 >= 80 AND p9 >= 8...,0.119112,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '..."
31,0.700000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_when_high,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.100319,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '..."
32,1.000000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.102378,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '..."
33,0.850000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_given_low,p1 >= 20 AND p2 >= 20 AND p3 >= 20 AND p4 >= 2...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.105932,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '..."
34,0.760000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_given_high,p1 >= 80 AND p2 >= 80 AND p3 >= 80 AND p4 >= 8...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.096248,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '..."
35,0.850000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_then_low,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 20 AND p7 >= 20 AND p8 >= 20 AND p9 >= 2...,0.109095,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '..."
36,0.760000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_then_high,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 80 AND p7 >= 80 AND p8 >= 80 AND p9 >= 8...,0.088947,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '..."
37,0.700000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_given_then_low,p1 >= 20 AND p2 >= 20 AND p3 >= 20 AND p4 >= 2...,p6 >= 20 AND p7 >= 20 AND p8 >= 20 AND p9 >= 2...,0.091436,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '..."
38,0.520000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_given_then_high,p1 >= 80 AND p2 >= 80 AND p3 >= 80 AND p4 >= 8...,p6 >= 80 AND p7 >= 80 AND p8 >= 80 AND p9 >= 8...,0.080144,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '..."
39,0.900000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_when_high,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.076207,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '..."

In [4]:
def extract_cfg_fields(row):
    cfg = row['config']  # já é um dict
    pw = cfg.get('parameter_weights', {})
    tw = cfg.get('tversky_weights', {})
    cw = cfg.get('conditional_weights', {})
    
    return pd.Series({
        'w_p1':    pw.get('p1'),
        'w_p10':   pw.get('p10'),
        'alpha':   tw.get('alpha'),
        'beta':    tw.get('beta'),
        'w_given': cw.get('given'),
        'w_when':  cw.get('when'),
        'w_then':  cw.get('then'),
    })

cfg_cols = df.apply(extract_cfg_fields, axis=1)
df_w = pd.concat([df, cfg_cols], axis=1)
df_w

,similarity_result,diagnosed_name,diagnosed_given,diagnosed_then,candidate_name,candidate_given,candidate_then,elapsed_time,config,w_p1,w_p10,alpha,beta,w_given,w_when,w_then
0,1.000000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.109511,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.9,0.1,1.0,1.0,1.0
1,0.875000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_given_low,p1 >= 20 AND p2 >= 20 AND p3 >= 20 AND p4 >= 2...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.144333,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.9,0.1,1.0,1.0,1.0
2,0.800000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_given_high,p1 >= 80 AND p2 >= 80 AND p3 >= 80 AND p4 >= 8...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.112845,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.9,0.1,1.0,1.0,1.0
3,0.875000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_then_low,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 20 AND p7 >= 20 AND p8 >= 20 AND p9 >= 2...,0.131997,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.9,0.1,1.0,1.0,1.0
4,0.800000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_then_high,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 80 AND p7 >= 80 AND p8 >= 80 AND p9 >= 8...,0.131111,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.9,0.1,1.0,1.0,1.0
5,0.750000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_given_then_low,p1 >= 20 AND p2 >= 20 AND p3 >= 20 AND p4 >= 2...,p6 >= 20 AND p7 >= 20 AND p8 >= 20 AND p9 >= 2...,0.118806,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.9,0.1,1.0,1.0,1.0
6,0.600000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_given_then_high,p1 >= 80 AND p2 >= 80 AND p3 >= 80 AND p4 >= 8...,p6 >= 80 AND p7 >= 80 AND p8 >= 80 AND p9 >= 8...,0.122367,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.9,0.1,1.0,1.0,1.0
7,0.833333,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_when_high,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.095124,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.9,0.1,1.0,1.0,1.0
8,1.000000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.135476,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.9,0.1,3.0,1.0,1.0
9,0.775000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_given_low,p1 >= 20 AND p2 >= 20 AND p3 >= 20 AND p4 >= 2...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.118131,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.9,0.1,3.0,1.0,1.0
10,0.640000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_given_high,p1 >= 80 AND p2 >= 80 AND p3 >= 80 AND p4 >= 8...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.093349,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.9,0.1,3.0,1.0,1.0
11,0.925000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_then_low,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 20 AND p7 >= 20 AND p8 >= 20 AND p9 >= 2...,0.084119,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.9,0.1,3.0,1.0,1.0
12,0.880000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_then_high,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 80 AND p7 >= 80 AND p8 >= 80 AND p9 >= 8...,0.086661,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.9,0.1,3.0,1.0,1.0
13,0.700000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_given_then_low,p1 >= 20 AND p2 >= 20 AND p3 >= 20 AND p4 >= 2...,p6 >= 20 AND p7 >= 20 AND p8 >= 20 AND p9 >= 2...,0.109106,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.9,0.1,3.0,1.0,1.0
14,0.520000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_given_then_high,p1 >= 80 AND p2 >= 80 AND p3 >= 80 AND p4 >= 8...,p6 >= 80 AND p7 >= 80 AND p8 >= 80 AND p9 >= 8...,0.099040,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.9,0.1,3.0,1.0,1.0
15,0.900000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_when_high,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.095989,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.9,0.1,3.0,1.0,1.0
16,1.000000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.108254,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.9,0.1,1.0,1.0,3.0
17,0.925000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_given_low,p1 >= 20 AND p2 >= 20 AND p3 >= 20 AND p4 >= 2...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.098002,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.9,0.1,1.0,1.0,3.0
18,0.880000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_given_high,p1 >= 80 AND p2 >= 80 AND p3 >= 80 AND p4 >= 8...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.103238,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.9,0.1,1.0,1.0,3.0
19,0.775000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_then_low,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 20 AND p7 >= 20 AND p8 >= 20 AND p9 >= 2...,0.110659,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.9,0.1,1.0,1.0,3.0
20,0.640000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_then_high,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 80 AND p7 >= 80 AND p8 >= 80 AND p9 >= 8...,0.087396,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.9,0.1,1.0,1.0,3.0
21,0.700000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_given_then_low,p1 >= 20 AND p2 >= 20 AND p3 >= 20 AND p4 >= 2...,p6 >= 20 AND p7 >= 20 AND p8 >= 20 AND p9 >= 2...,0.097267,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.9,0.1,1.0,1.0,3.0
22,0.520000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_given_then_high,p1 >= 80 AND p2 >= 80 AND p3 >= 80 AND p4 >= 8...,p6 >= 80 AND p7 >= 80 AND p8 >= 80 AND p9 >= 8...,0.099623,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.9,0.1,1.0,1.0,3.0
23,0.900000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_when_high,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.092654,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.9,0.1,1.0,1.0,3.0
24,1.000000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.106620,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.9,0.1,1.0,3.0,1.0
25,0.925000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_given_low,p1 >= 20 AND p2 >= 20 AND p3 >= 20 AND p4 >= 2...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.103085,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.9,0.1,1.0,3.0,1.0
26,0.880000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_given_high,p1 >= 80 AND p2 >= 80 AND p3 >= 80 AND p4 >= 8...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.100841,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.9,0.1,1.0,3.0,1.0
27,0.925000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_then_low,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 20 AND p7 >= 20 AND p8 >= 20 AND p9 >= 2...,0.096083,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.9,0.1,1.0,3.0,1.0
28,0.880000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_then_high,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 80 AND p7 >= 80 AND p8 >= 80 AND p9 >= 8...,0.090864,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.9,0.1,1.0,3.0,1.0
29,0.850000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_given_then_low,p1 >= 20 AND p2 >= 20 AND p3 >= 20 AND p4 >= 2...,p6 >= 20 AND p7 >= 20 AND p8 >= 20 AND p9 >= 2...,0.119998,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.9,0.1,1.0,3.0,1.0
30,0.760000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_given_then_high,p1 >= 80 AND p2 >= 80 AND p3 >= 80 AND p4 >= 8...,p6 >= 80 AND p7 >= 80 AND p8 >= 80 AND p9 >= 8...,0.119112,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.9,0.1,1.0,3.0,1.0
31,0.700000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_when_high,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.100319,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.9,0.1,1.0,3.0,1.0
32,1.000000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.102378,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.9,0.1,2.0,1.0,2.0
33,0.850000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_given_low,p1 >= 20 AND p2 >= 20 AND p3 >= 20 AND p4 >= 2...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.105932,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.9,0.1,2.0,1.0,2.0
34,0.760000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_given_high,p1 >= 80 AND p2 >= 80 AND p3 >= 80 AND p4 >= 8...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.096248,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.9,0.1,2.0,1.0,2.0
35,0.850000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_then_low,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 20 AND p7 >= 20 AND p8 >= 20 AND p9 >= 2...,0.109095,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.9,0.1,2.0,1.0,2.0
36,0.760000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_then_high,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 80 AND p7 >= 80 AND p8 >= 80 AND p9 >= 8...,0.088947,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.9,0.1,2.0,1.0,2.0
37,0.700000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_given_then_low,p1 >= 20 AND p2 >= 20 AND p3 >= 20 AND p4 >= 2...,p6 >= 20 AND p7 >= 20 AND p8 >= 20 AND p9 >= 2...,0.091436,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.9,0.1,2.0,1.0,2.0
38,0.520000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_given_then_high,p1 >= 80 AND p2 >= 80 AND p3 >= 80 AND p4 >= 8...,p6 >= 80 AND p7 >= 80 AND p8 >= 80 AND p9 >= 8...,0.080144,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.9,0.1,2.0,1.0,2.0
39,0.900000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_when_high,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.076207,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.9,0.1,2.0,1.0,2.0

In [6]:
import plotly.express as px
import pandas as pd

df_plot = df_w.copy()

# 1) Mapeia nomes internos -> labels técnicos (RQ3.3)
label_map = {
    "cand_baseline":          "baseline",
    "cand_given_low":         "given-low",
    "cand_given_high":        "given-high",
    "cand_then_low":          "then-low",
    "cand_then_high":         "then-high",
    "cand_given_then_low":    "given+then-low",
    "cand_given_then_high":   "given+then-high",
    "cand_when_high":         "when-high",
}

df_plot["candidate_label"] = df_plot["candidate_name"].map(label_map).fillna(df_plot["candidate_name"])

# Ordem dos candidatos no eixo Y (pode ajustar se quiser outra ordem)
candidate_order = [
    "baseline",
    "given-low",
    "given-high",
    "then-low",
    "then-high",
    "given+then-low",
    "given+then-high",
    "when-high",
]
df_plot["candidate_label"] = pd.Categorical(
    df_plot["candidate_label"],
    categories=candidate_order,
    ordered=True
)

# 2) Cria rótulo da configuração de pesos de cláusula (w_given, w_when, w_then)
#    Mapeando para as 5 configs definidas na tabela (C1–C5)
config_map = {
    (1.0, 1.0, 1.0): "C1 (1,1,1)",
    (3.0, 1.0, 1.0): "C2 (3,1,1)",
    (1.0, 1.0, 3.0): "C3 (1,1,3)",
    (1.0, 3.0, 1.0): "C4 (1,3,1)",
    (2.0, 1.0, 2.0): "C5 (2,1,2)",
}

def label_clause_config(row):
    key = (row["w_given"], row["w_when"], row["w_then"])
    return config_map.get(
        key,
        f"({row['w_given']:.1g},{row['w_when']:.1g},{row['w_then']:.1g})"
    )

df_plot["clause_config"] = df_plot.apply(label_clause_config, axis=1)

# Ordem das configurações no eixo X
config_order = ["C1 (1,1,1)", "C2 (3,1,1)", "C3 (1,1,3)", "C4 (1,3,1)", "C5 (2,1,2)"]
df_plot["clause_config"] = pd.Categorical(
    df_plot["clause_config"],
    categories=config_order,
    ordered=True
)

# 3) pivot: linhas = candidato, colunas = configuração (pesos de cláusula)
heat_df = df_plot.pivot_table(
    index="candidate_label",
    columns="clause_config",
    values="similarity_result"
)

fig = px.imshow(
    heat_df,
    text_auto=".2f",
    aspect="auto",
    labels={
        "x": "Clause-weight configuration (w_given, w_when, w_then)",
        "y": "Candidate",
        "color": "Similarity"
    },
    color_continuous_scale="Viridis"
)

# Mantém a escala de cores consistente
fig.update_coloraxes(
    cmin=df_plot["similarity_result"].min(),
    cmax=df_plot["similarity_result"].max()
)

fig.update_layout(
    title=None,
    width=800,
    height=450,
    margin=dict(l=150, r=40, t=30, b=80),
    font=dict(size=12),
)

fig.update_xaxes(showgrid=False, tickangle=-15)
fig.update_yaxes(showgrid=False)

fig.show()

C:\Users\lucas_alves\AppData\Local\Temp\ipykernel_53984\2185669392.py:65: FutureWarning:

The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior

In [7]:
import plotly.express as px
import pandas as pd

df_plot = df_w.copy()

# 1) Mapeia nomes internos -> labels técnicos (RQ3.3)
label_map = {
    "cand_baseline":          "baseline",
    "cand_given_low":         "given-low",
    "cand_given_high":        "given-high",
    "cand_then_low":          "then-low",
    "cand_then_high":         "then-high",
    "cand_given_then_low":    "given+then-low",
    "cand_given_then_high":   "given+then-high",
    "cand_when_high":         "when-high",
}

df_plot["candidate_label"] = df_plot["candidate_name"].map(label_map).fillna(df_plot["candidate_name"])

# Ordem dos candidatos na legenda (e, se quiser, em outras figuras)
candidate_order = [
    "baseline",
    "given-low",
    "given-high",
    "then-low",
    "then-high",
    "given+then-low",
    "given+then-high",
    "when-high",
]
df_plot["candidate_label"] = pd.Categorical(
    df_plot["candidate_label"],
    categories=candidate_order,
    ordered=True
)

# 2) Cria rótulo da configuração de pesos de cláusula (w_given, w_when, w_then)
config_map = {
    (1.0, 1.0, 1.0): "C1 (1,1,1)",
    (3.0, 1.0, 1.0): "C2 (3,1,1)",
    (1.0, 1.0, 3.0): "C3 (1,1,3)",
    (1.0, 3.0, 1.0): "C4 (1,3,1)",
    (2.0, 1.0, 2.0): "C5 (2,1,2)",
}

def label_clause_config(row):
    key = (row["w_given"], row["w_when"], row["w_then"])
    return config_map.get(
        key,
        f"({row['w_given']:.1g},{row['w_when']:.1g},{row['w_then']:.1g})"
    )

df_plot["clause_regime"] = df_plot.apply(label_clause_config, axis=1)

config_order = ["C1 (1,1,1)", "C2 (3,1,1)", "C3 (1,1,3)", "C4 (1,3,1)", "C5 (2,1,2)"]
df_plot["clause_regime"] = pd.Categorical(
    df_plot["clause_regime"],
    categories=config_order,
    ordered=True
)

# 3) Gráfico de linhas: X = regime de pesos, Y = similaridade, uma linha por candidato
fig = px.line(
    df_plot,
    x="clause_regime",
    y="similarity_result",
    color="candidate_label",
    markers=True,
    labels={
        "clause_regime": "Clause-weight configuration (w_given, w_when, w_then)",
        "similarity_result": "Similarity",
        "candidate_label": "Candidate"
    }
)

fig.update_traces(mode="lines+markers")

fig.update_layout(
    width=900,
    height=400,
    margin=dict(l=60, r=20, t=30, b=80),
    xaxis_tickangle=-20,
    legend_title_text="Candidate"
)

fig.show()

In [8]:
import plotly.express as px
import pandas as pd

df_plot = df_w.copy()

# labels técnicos (mesmo mapeamento da RQ3.3)
label_map = {
    "cand_baseline":          "baseline",
    "cand_given_low":         "given-low",
    "cand_given_high":        "given-high",
    "cand_then_low":          "then-low",
    "cand_then_high":         "then-high",
    "cand_given_then_low":    "given+then-low",
    "cand_given_then_high":   "given+then-high",
    "cand_when_high":         "when-high",
}
df_plot["candidate_label"] = df_plot["candidate_name"].map(label_map).fillna(df_plot["candidate_name"])

candidate_order = [
    "baseline",
    "given-low",
    "given-high",
    "then-low",
    "then-high",
    "given+then-low",
    "given+then-high",
    "when-high",
]
df_plot["candidate_label"] = pd.Categorical(
    df_plot["candidate_label"],
    categories=candidate_order,
    ordered=True
)

# rótulo das configurações de pesos de cláusula
config_map = {
    (1.0, 1.0, 1.0): "C1 (1,1,1)",
    (3.0, 1.0, 1.0): "C2 (3,1,1)",
    (1.0, 1.0, 3.0): "C3 (1,1,3)",
    (1.0, 3.0, 1.0): "C4 (1,3,1)",
    (2.0, 1.0, 2.0): "C5 (2,1,2)",
}

def label_clause_config(row):
    key = (row["w_given"], row["w_when"], row["w_then"])
    return config_map.get(key, f"({row['w_given']:.1g},{row['w_when']:.1g},{row['w_then']:.1g})")

df_plot["clause_regime"] = df_plot.apply(label_clause_config, axis=1)

config_order = ["C1 (1,1,1)", "C2 (3,1,1)", "C3 (1,1,3)", "C4 (1,3,1)", "C5 (2,1,2)"]
df_plot["clause_regime"] = pd.Categorical(
    df_plot["clause_regime"],
    categories=config_order,
    ordered=True
)

fig = px.bar(
    df_plot,
    x="candidate_label",
    y="similarity_result",
    color="clause_regime",
    barmode="group",
    labels={
        "candidate_label": "Candidate",
        "similarity_result": "Similarity",
        "clause_regime": "Clause-weight configuration"
    },
)

fig.update_layout(
    width=900,
    height=450,
    margin=dict(l=60, r=20, t=30, b=80),
    legend_title_text="Clause weights (w_g, w_w, w_t)",
)

fig.show()

In [9]:
df_plot = df_w.copy()
# (reutiliza o mapeamento de labels de cima)

# cria rótulo de regime de cláusula
df_plot["clause_regime"] = df_plot.apply(label_clause_config, axis=1)

# separa baseline de pesos (C1)
df_c1 = df_plot[df_plot["clause_regime"] == "C1 (1,1,1)"][["candidate_name", "similarity_result"]]
df_c1 = df_c1.rename(columns={"similarity_result": "sim_c1"})

# junta para ter sim_c1 em todas as linhas
df_delta = df_plot.merge(df_c1, on="candidate_name", how="left")
df_delta["delta_similarity"] = df_delta["similarity_result"] - df_delta["sim_c1"]



df_delta["candidate_label"] = df_delta["candidate_name"].map(label_map).fillna(df_delta["candidate_name"])
df_delta["candidate_label"] = pd.Categorical(
    df_delta["candidate_label"],
    categories=candidate_order,
    ordered=True
)

fig = px.bar(
    df_delta[df_delta["clause_regime"] != "C1 (1,1,1)"],  # se quiser ignorar o delta = 0 do C1
    x="candidate_label",
    y="delta_similarity",
    color="clause_regime",
    barmode="group",
    labels={
        "candidate_label": "Candidate",
        "delta_similarity": "Δ Similarity (config − C1)",
        "clause_regime": "Clause-weight configuration"
    },
)

fig.update_layout(
    width=900,
    height=450,
    margin=dict(l=60, r=20, t=30, b=80),
    legend_title_text="Clause weights (w_g, w_w, w_t)",
)

fig.show()

In [12]:
# ensure df_plot has the candidate_label and clause_regime columns
df_plot = df_w.copy()

# labels técnicos (mesmo mapeamento usado nas células anteriores)
label_map = {
    "cand_baseline":          "baseline",
    "cand_given_low":         "given-low",
    "cand_given_high":        "given-high",
    "cand_then_low":          "then-low",
    "cand_then_high":         "then-high",
    "cand_given_then_low":    "given+then-low",
    "cand_given_then_high":   "given+then-high",
    "cand_when_high":         "when-high",
}
candidate_order = [
    "baseline",
    "given-low",
    "given-high",
    "then-low",
    "then-high",
    "given+then-low",
    "given+then-high",
    "when-high",
]

df_plot["candidate_label"] = df_plot["candidate_name"].map(label_map).fillna(df_plot["candidate_name"])
df_plot["candidate_label"] = pd.Categorical(
    df_plot["candidate_label"],
    categories=candidate_order,
    ordered=True
)

# ensure clause_regime exists (same mapping as used before)
config_map = {
    (1.0, 1.0, 1.0): "C1 (1,1,1)",
    (3.0, 1.0, 1.0): "C2 (3,1,1)",
    (1.0, 1.0, 3.0): "C3 (1,1,3)",
    (1.0, 3.0, 1.0): "C4 (1,3,1)",
    (2.0, 1.0, 2.0): "C5 (2,1,2)",
}
def label_clause_config(row):
    key = (row["w_given"], row["w_when"], row["w_then"])
    return config_map.get(
        key,
        f"({row['w_given']:.1g},{row['w_when']:.1g},{row['w_then']:.1g})"
    )

df_plot["clause_regime"] = df_plot.apply(label_clause_config, axis=1)

fig = px.line(
    df_plot,
    x="clause_regime",
    y="similarity_result",
    facet_col="candidate_label",
    facet_col_wrap=4,
    markers=True,
    labels={
        "clause_regime": "Clause-weight configuration",
        "similarity_result": "Similarity"
    },
    title="Similarity per clause-weight configuration, one panel per candidate"
)

fig.update_traces(mode="lines+markers")

fig.update_layout(
    width=1000,
    height=600,
    margin=dict(l=40, r=20, t=60, b=80),
)

# gira os rótulos do eixo x em todos os facets
fig.for_each_xaxis(lambda ax: ax.update(tickangle=-30))

fig.show()

In [13]:
import pandas as pd

df_rank = df_plot.copy()

# rank 1 = maior similaridade
df_rank["rank"] = (
    df_rank
    .groupby("clause_regime")["similarity_result"]
    .rank(method="dense", ascending=False)
)

import plotly.express as px

fig = px.line(
    df_rank,
    x="clause_regime",
    y="rank",
    color="candidate_label",
    markers=True,
    labels={
        "clause_regime": "Clause-weight configuration",
        "rank": "Rank (1 = most similar)",
        "candidate_label": "Candidate"
    },
    title="Change in candidate ranking across clause-weight configurations"
)

fig.update_traces(mode="lines+markers")

fig.update_layout(
    width=900,
    height=450,
    margin=dict(l=60, r=20, t=40, b=120),
    legend_title_text="Candidate",
    xaxis_tickangle=-20,
    yaxis_autorange="reversed"  # para rank 1 ficar em cima
)

fig.show()