In [11]:
import pandas as pd
import json

# Caminho para seu arquivo
file_path = 'similarity_results.jsonl'

# Carrega cada linha do arquivo como um dicionário
data = []
with open(file_path, 'r', encoding='utf-8') as f:
    for line in f:
        item = json.loads(line)
        # Extrai campos desejados
        row = {
            'similarity_result': item['similarity_result'],
            'diagnosed_name': item['diagnosed']['name'],
            'diagnosed_given': item['diagnosed']['given'],
            'diagnosed_then': item['diagnosed']['then'],
            'candidate_name': item['candidate']['name'],
            'candidate_given': item['candidate']['given'],
            'candidate_then': item['candidate']['then'],
            'elapsed_time': item['elapsed_time'],
            'config': item['config'],
        }
        data.append(row)

# Cria o DataFrame
df = pd.DataFrame(data)

# Exemplo: mostra as primeiras linhas
df

,similarity_result,diagnosed_name,diagnosed_given,diagnosed_then,candidate_name,candidate_given,candidate_then,elapsed_time,config
0,1.000000,diagnosed_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,diagnosed_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.152671,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
1,0.585686,diagnosed_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,1,p1 <= 40 AND p2 >= 55 AND p3 >= 50 AND p4 <= 6...,p10 >= 55 AND p16 > 60 AND p6 < 65 AND p7 <= 5...,0.145927,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
2,0.400000,diagnosed_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,2,p4 < 60 AND p8 > 55 AND p1 >= 50 AND p14 <= 40,p14 > 65 AND p17 <= 60 AND p1 > 40 AND p6 >= 5...,0.101953,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
3,0.556667,diagnosed_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,3,p1 < 40 AND p2 > 55 AND p3 < 60 AND p4 > 60 AN...,p10 > 65 AND p6 <= 65 AND p7 < 40 AND p8 > 65 ...,0.105955,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
4,0.430927,diagnosed_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,4,p9 < 65 AND p20 < 50 AND p2 >= 45 AND p16 >= 6...,p3 < 65 AND p16 < 40 AND p8 >= 55 AND p18 >= 4...,0.121946,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
...,...,...,...,...,...,...,...,...,...
320,0.333333,remove_90_then,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50,20,p7 < 45 AND p18 < 55 AND p12 < 60 AND p10 <= 55,p17 > 45 AND p9 < 55 AND p2 <= 40 AND p1 > 65 ...,0.069738,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
321,0.689307,remove_90_then,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50,21,p1 >= 60 AND p2 >= 45 AND p3 > 45 AND p4 <= 50...,p10 <= 60 AND p6 > 60 AND p7 <= 50 AND p8 < 60...,0.100911,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
322,0.556161,remove_90_then,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50,22,p1 < 40 AND p2 > 65 AND p3 >= 45 AND p4 >= 55 ...,p10 >= 45 AND p20 >= 45 AND p6 <= 50 AND p7 > ...,0.071804,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
323,0.415501,remove_90_then,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50,23,p18 >= 50 AND p3 < 45 AND p1 > 45 AND p5 > 50 ...,p7 >= 50 AND p13 <= 45 AND p12 <= 50 AND p19 <...,0.080142,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
324,0.392374,remove_90_then,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50,24,p4 < 60 AND p14 <= 65 AND p10 < 45 AND p13 > 5...,p14 >= 60 AND p1 <= 65 AND p9 > 65 AND p10 > 5...,0.067570,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."

In [12]:
df_baseline = df[df['diagnosed_name'] == 'diagnosed_baseline']
df_baseline

,similarity_result,diagnosed_name,diagnosed_given,diagnosed_then,candidate_name,candidate_given,candidate_then,elapsed_time,config
0,1.000000,diagnosed_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,diagnosed_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.152671,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
1,0.585686,diagnosed_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,1,p1 <= 40 AND p2 >= 55 AND p3 >= 50 AND p4 <= 6...,p10 >= 55 AND p16 > 60 AND p6 < 65 AND p7 <= 5...,0.145927,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
2,0.400000,diagnosed_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,2,p4 < 60 AND p8 > 55 AND p1 >= 50 AND p14 <= 40,p14 > 65 AND p17 <= 60 AND p1 > 40 AND p6 >= 5...,0.101953,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
3,0.556667,diagnosed_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,3,p1 < 40 AND p2 > 55 AND p3 < 60 AND p4 > 60 AN...,p10 > 65 AND p6 <= 65 AND p7 < 40 AND p8 > 65 ...,0.105955,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
4,0.430927,diagnosed_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,4,p9 < 65 AND p20 < 50 AND p2 >= 45 AND p16 >= 6...,p3 < 65 AND p16 < 40 AND p8 >= 55 AND p18 >= 4...,0.121946,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
5,0.751817,diagnosed_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,5,p1 >= 45 AND p2 < 65 AND p3 >= 55 AND p4 >= 40...,p10 < 45 AND p6 <= 50 AND p7 >= 40 AND p8 >= 4...,0.174056,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
6,0.906797,diagnosed_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,6,p1 >= 55 AND p18 >= 55 AND p2 >= 60 AND p3 >= ...,p10 >= 60 AND p6 >= 60 AND p7 >= 55 AND p8 >= ...,0.114045,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
7,0.946797,diagnosed_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,7,p1 >= 50 AND p2 >= 50 AND p20 >= 60 AND p3 >= ...,p10 >= 50 AND p6 >= 50 AND p7 >= 60 AND p8 >= ...,0.084805,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
8,0.679495,diagnosed_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,8,p1 >= 60 AND p2 > 60 AND p3 >= 65 AND p4 < 40 ...,p10 >= 50 AND p6 < 55 AND p7 > 45 AND p8 > 40 ...,0.106535,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
9,0.714676,diagnosed_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,9,p1 >= 55 AND p17 <= 60 AND p2 > 60 AND p3 > 45...,p10 < 55 AND p6 < 60 AND p7 >= 65 AND p8 > 65 ...,0.094680,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
10,0.614505,diagnosed_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,10,p1 >= 40 AND p3 > 45 AND p5 > 55 AND p17 > 55 ...,p15 > 65 AND p6 > 45 AND p17 > 60 AND p10 > 50,0.078131,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
11,0.369444,diagnosed_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,11,p17 <= 45 AND p18 < 60 AND p4 > 55,p13 < 60 AND p19 <= 50 AND p15 >= 55 AND p16 >...,0.083975,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
12,0.900131,diagnosed_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,12,p1 >= 60 AND p2 >= 60 AND p3 >= 60 AND p4 >= 6...,p10 >= 55 AND p16 >= 60 AND p6 >= 60 AND p7 >=...,0.105582,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
13,0.333333,diagnosed_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,13,p16 <= 45 AND p13 < 45 AND p1 >= 50 AND p3 < 5...,p8 < 60 AND p18 >= 45 AND p19 < 50,0.094246,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
14,0.333333,diagnosed_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,14,p7 > 55 AND p6 > 45 AND p19 < 55 AND p18 <= 40...,p3 >= 55 AND p7 > 40 AND p11 <= 65 AND p10 < 50,0.104216,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
15,0.840131,diagnosed_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,15,p1 >= 55 AND p13 >= 50 AND p2 >= 60 AND p3 >= ...,p10 >= 55 AND p16 >= 60 AND p7 >= 55 AND p8 >=...,0.083125,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
16,0.635686,diagnosed_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,16,p1 > 40 AND p19 <= 65 AND p2 > 65 AND p3 >= 65...,p10 <= 65 AND p6 <= 65 AND p7 >= 55 AND p8 <= ...,0.150105,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
17,0.469388,diagnosed_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,17,p3 > 50 AND p18 <= 65 AND p4 >= 50 AND p13 >= 45,p9 > 65 AND p2 <= 55 AND p17 >= 60,0.123156,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
18,0.873464,diagnosed_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,18,p1 >= 50 AND p19 >= 50 AND p3 >= 55 AND p4 >= ...,p10 >= 60 AND p18 >= 55 AND p6 >= 50 AND p7 >=...,0.080632,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
19,0.802828,diagnosed_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,19,p1 > 40 AND p2 > 65 AND p3 >= 65 AND p4 > 50 A...,p10 > 45 AND p6 > 50 AND p7 >= 55 AND p8 <= 55...,0.093495,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
20,0.333333,diagnosed_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,20,p7 < 45 AND p18 < 55 AND p12 < 60 AND p10 <= 55,p17 > 45 AND p9 < 55 AND p2 <= 40 AND p1 > 65 ...,0.074718,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
21,0.644545,diagnosed_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,21,p1 >= 60 AND p2 >= 45 AND p3 > 45 AND p4 <= 50...,p10 <= 60 AND p6 > 60 AND p7 <= 50 AND p8 < 60...,0.136467,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
22,0.733565,diagnosed_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,22,p1 < 40 AND p2 > 65 AND p3 >= 45 AND p4 >= 55 ...,p10 >= 45 AND p20 >= 45 AND p6 <= 50 AND p7 > ...,0.099781,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
23,0.474475,diagnosed_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,23,p18 >= 50 AND p3 < 45 AND p1 > 45 AND p5 > 50 ...,p7 >= 50 AND p13 <= 45 AND p12 <= 50 AND p19 <...,0.113319,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
24,0.529411,diagnosed_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,24,p4 < 60 AND p14 <= 65 AND p10 < 45 AND p13 > 5...,p14 >= 60 AND p1 <= 65 AND p9 > 65 AND p10 > 5...,0.103854,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."

In [13]:
import plotly.express as px

fig = px.scatter(
    df_baseline,
    x='candidate_name',           # eixo X: nome do candidato
    y='similarity_result',        # eixo Y: similaridade
    color='similarity_result',    # cor dos pontos pela similaridade
    hover_data=['candidate_given', 'candidate_then'],  # informações extras no hover
    title='Similaridade por Candidato (Diagnosed Baseline)'
)
fig.update_layout(
    xaxis_title='Candidato',
    yaxis_title='Similaridade',
    template='plotly_white'
)
fig.show()

In [14]:
df.index

RangeIndex(start=0, stop=325, step=1)

In [15]:
import pandas as pd
import plotly.graph_objects as go

# 1. Carregar o CSV
df = pd.read_csv('temp.csv')

# 2. Lista de candidatos a manter (ajuste conforme seu DataFrame: número ou string)
keep_candidates = ["16", "22", "8", "9", "1", "10", "3", "diagnosed_baseline"]

# 3. Ordem das execuções (ajuste conforme necessário)
diagnosis_order = [
    "remove_90_then", "remove_60_then", "remove_30_then", 
    "remove_90_given", "remove_60_given", "remove_30_given", 
    "diagnosed_baseline", 
    "add_30_given", "add_60_given", "add_90_given", 
    "add_30_then", "add_60_then", "add_90_then"
]

# 4. Filtrar DataFrame
df = df[df["candidate_name"].astype(str).isin(keep_candidates)]

# 5. Montar tabela pivô
df_pivot = df.pivot(index="candidate_name", columns="diagnosed_name", values="similarity_result")
df_pivot = df_pivot[[col for col in diagnosis_order if col in df_pivot.columns]]
df_pivot = df_pivot.loc[keep_candidates]  # Mantém a ordem dos candidatos

# 6. Plotar o Slope Chart
fig = go.Figure()
for cand in df_pivot.index:
    fig.add_trace(go.Scatter(
        x=df_pivot.columns,
        y=df_pivot.loc[cand],
        mode='lines+markers',
        name=str(cand)
    ))
fig.update_layout(
    title='Slope Chart - Mudança de Similaridade dos Candidatos Selecionados',
    xaxis_title='Execução Diagnóstica',
    yaxis_title='Similaridade',
    xaxis=dict(tickangle=-45)
)
fig.show()

In [16]:
import pandas as pd
import plotly.graph_objects as go

# Carregar e preparar os dados
df = pd.read_csv('temp.csv')
keep_candidates = ["16", "22", "8", "9", "1", "10", "3","diagnosed_baseline"]
diagnosis_order = [
    "remove_90_then", "remove_60_then", "remove_30_then", 
    "remove_90_given", "remove_60_given", "remove_30_given", 
    "diagnosed_baseline", 
    "add_30_given", "add_60_given", "add_90_given", 
    "add_30_then", "add_60_then", "add_90_then"
]

df = df[df["candidate_name"].astype(str).isin(keep_candidates)]
df_pivot = df.pivot(index="candidate_name", columns="diagnosed_name", values="similarity_result")
df_pivot = df_pivot[[col for col in diagnosis_order if col in df_pivot.columns]]
df_pivot = df_pivot.loc[keep_candidates]  # Mantém a ordem dos candidatos

# Gerar o Slope Chart com melhor proporção e destaque visual
fig = go.Figure()
for cand in df_pivot.index:
    fig.add_trace(go.Scatter(
        x=df_pivot.columns,
        y=df_pivot.loc[cand],
        mode='lines+markers+text',
        text=[f'{y:.2f}' for y in df_pivot.loc[cand]],  # Mostra o valor em cada ponto
        textposition="top center",
        name=str(cand),
        line=dict(width=4),
        marker=dict(size=12)
    ))
fig.update_layout(
    title='Slope Chart: Mudança de Similaridade dos Candidatos Selecionados',
    xaxis_title='Execução Diagnóstica',
    yaxis_title='Similaridade',
    xaxis=dict(tickangle=-45),
    width=850,   # largura reduzida
    height=600,  # altura aumentada
    legend=dict(
        title="Candidatos",
        yanchor="top",
        y=0.99,
        xanchor="left",
        x=0.01
    ),
    margin=dict(l=40, r=40, t=70, b=90)
)
fig.show()

In [17]:
import pandas as pd
import plotly.graph_objects as go

# Carregar e preparar os dados
df = pd.read_csv('temp.csv')
keep_candidates = ["16", "22", "8", "9", "1", "10", "3"]
diagnosis_order = [
    "remove_90_then", "remove_60_then", "remove_30_then", 
    "remove_90_given", "remove_60_given", "remove_30_given", 
    "diagnosed_baseline", 
    "add_30_given", "add_60_given", "add_90_given", 
    "add_30_then", "add_60_then", "add_90_then"
]

df = df[df["candidate_name"].astype(str).isin(keep_candidates)]
df_pivot = df.pivot(index="candidate_name", columns="diagnosed_name", values="similarity_result")
df_pivot = df_pivot[[col for col in diagnosis_order if col in df_pivot.columns]]
df_pivot = df_pivot.loc[keep_candidates]

# Destaque um candidato, por exemplo, '16' (ou mude para outro)
main_cand = "16"

fig = go.Figure()

for cand in df_pivot.index:
    if cand == main_cand:
        fig.add_trace(go.Scatter(
            x=df_pivot.columns,
            y=df_pivot.loc[cand],
            mode='lines+markers+text',
            name=f"Top: {cand}",
            line=dict(width=5, color="crimson"),
            marker=dict(size=15, color="crimson"),
            text=["", "", "", "", "", "", f"{df_pivot.loc[cand, 'diagnosed_baseline']:.2f}", "", "", "", "", "", ""],
            textposition="top center"
        ))
    else:
        fig.add_trace(go.Scatter(
            x=df_pivot.columns,
            y=df_pivot.loc[cand],
            mode='lines+markers',
            name=str(cand),
            line=dict(width=2, dash="dot", color="gray"),
            marker=dict(size=9, color="gray")
        ))

fig.update_layout(
    title='Slope Chart (Destacando Top)',
    xaxis_title='Execução Diagnóstica',
    yaxis_title='Similaridade',
    xaxis=dict(tickangle=-45),
    width=800,
    height=650,
    legend=dict(title="Candidatos", yanchor="top", y=0.99, xanchor="left", x=0.01),
    margin=dict(l=40, r=40, t=70, b=90)
)
fig.show()

In [18]:
import pandas as pd
import plotly.graph_objects as go

# Carregar e preparar os dados
df = pd.read_csv('temp.csv')
keep_candidates = ["16", "22", "8", "9", "1", "10", "3"]
diagnosis_order = [
    "remove_90_then", "remove_60_then", "remove_30_then", 
    "remove_90_given", "remove_60_given", "remove_30_given", 
    "diagnosed_baseline", 
    "add_30_given", "add_60_given", "add_90_given", 
    "add_30_then", "add_60_then", "add_90_then"
]

# Filtrar candidatos
df = df[df["candidate_name"].astype(str).isin(keep_candidates)]
# Montar matriz pivô
df_pivot = df.pivot(index="candidate_name", columns="diagnosed_name", values="similarity_result")
df_pivot = df_pivot[[col for col in diagnosis_order if col in df_pivot.columns]]
df_pivot = df_pivot.loc[keep_candidates]

# Gerar ranking (1 = topo) para cada execução
df_rank = df_pivot.rank(ascending=False, axis=0, method='min')

# Plotar o bump chart
fig = go.Figure()
for cand in df_rank.index:
    fig.add_trace(go.Scatter(
        x=df_rank.columns,
        y=df_rank.loc[cand],
        mode='lines+markers+text',
        name=str(cand),
        line=dict(width=4),
        marker=dict(size=13),
        text=["" if i not in [0, len(df_rank.columns)-1] else str(cand) for i in range(len(df_rank.columns))],
        textposition="bottom center"
    ))
fig.update_layout(
    title='Bump Chart - Ranking dos Candidatos ao Longo das Execuções',
    xaxis_title='Execução Diagnóstica',
    yaxis_title='Ranking (1 = topo)',
    yaxis=dict(autorange='reversed', dtick=1),  # 1 no topo!
    xaxis=dict(tickangle=-45),
    width=900,
    height=650,
    legend=dict(title="Candidatos", yanchor="top", y=0.99, xanchor="left", x=0.01),
    margin=dict(l=40, r=40, t=70, b=90)
)
fig.show()

In [20]:
import pandas as pd
import plotly.graph_objects as go

# Carregar e preparar os dados
keep_candidates = ["16", "22", "8", "9", "1", "10", "3"]
diagnosis_order = [
    "remove_90_then", "remove_60_then", "remove_30_then", 
    "remove_90_given", "remove_60_given", "remove_30_given", 
    "diagnosed_baseline", 
    "add_30_given", "add_60_given", "add_90_given", 
    "add_30_then", "add_60_then", "add_90_then"
]

df = df[df["candidate_name"].astype(str).isin(keep_candidates)]
df_pivot = df.pivot(index="candidate_name", columns="diagnosed_name", values="similarity_result")
df_pivot = df_pivot[[col for col in diagnosis_order if col in df_pivot.columns]]
df_pivot = df_pivot.loc[keep_candidates]
df_rank = df_pivot.rank(ascending=False, axis=0, method='min')

fig = go.Figure()
for cand in df_rank.index:
    fig.add_trace(go.Scatter(
        x=df_rank.columns,
        y=df_rank.loc[cand],
        mode='lines+markers+text',
        name=str(cand),
        line=dict(width=4),
        marker=dict(size=13),
        text=["" if i not in [0, len(df_rank.columns)-1] else str(cand) for i in range(len(df_rank.columns))],
        textposition="bottom center"
    ))
fig.update_layout(
    title='Bump Chart - Ranking dos Candidatos ao Longo das Execuções',
    xaxis_title='Execução Diagnóstica',
    yaxis_title='Ranking (1 = topo)',
    yaxis=dict(autorange='reversed', dtick=1),
    xaxis=dict(
        tickangle=-45,
        categoryorder='array',
        categoryarray=diagnosis_order,
        tickvals=diagnosis_order,
        ticktext=diagnosis_order
    ),
    width=1500,   # largura aumentada!
    height=700,
    legend=dict(title="Candidatos", yanchor="top", y=0.99, xanchor="left", x=0.01),
    margin=dict(l=40, r=40, t=70, b=90)
)
fig.show()

In [ ]:
--------+

SyntaxError: invalid syntax (2819048361.py, line 1)