In [1]:
import pandas as pd
import json

# Caminho para seu arquivo
file_path = 'similarity_results.jsonl'

# Carrega cada linha do arquivo como um dicionário
data = []
with open(file_path, 'r', encoding='utf-8') as f:
    for line in f:
        item = json.loads(line)
        # Extrai campos desejados
        row = {
            'similarity_result': item['similarity_result'],
            'diagnosed_name': item['diagnosed']['name'],
            'diagnosed_given': item['diagnosed']['given'],
            'diagnosed_then': item['diagnosed']['then'],
            'candidate_name': item['candidate']['name'],
            'candidate_given': item['candidate']['given'],
            'candidate_then': item['candidate']['then'],
            'elapsed_time': item['elapsed_time'],
            'config': item['config'],
        }
        data.append(row)

# Cria o DataFrame
df = pd.DataFrame(data)

# Exemplo: mostra as primeiras linhas
df

,similarity_result,diagnosed_name,diagnosed_given,diagnosed_then,candidate_name,candidate_given,candidate_then,elapsed_time,config
0,1.000000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.093598,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
1,0.585686,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,1,p1 <= 40 AND p2 >= 55 AND p3 >= 50 AND p4 <= 6...,p10 >= 55 AND p16 > 60 AND p6 < 65 AND p7 <= 5...,0.121454,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
2,0.400000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,2,p4 < 60 AND p8 > 55 AND p1 >= 50 AND p14 <= 40,p14 > 65 AND p17 <= 60 AND p1 > 40 AND p6 >= 5...,0.080429,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
3,0.556667,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,3,p1 < 40 AND p2 > 55 AND p3 < 60 AND p4 > 60 AN...,p10 > 65 AND p6 <= 65 AND p7 < 40 AND p8 > 65 ...,0.095145,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
4,0.430927,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,4,p9 < 65 AND p20 < 50 AND p2 >= 45 AND p16 >= 6...,p3 < 65 AND p16 < 40 AND p8 >= 55 AND p18 >= 4...,0.101158,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
...,...,...,...,...,...,...,...,...,...
320,0.333333,remove_90_then,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50,20,p7 < 45 AND p18 < 55 AND p12 < 60 AND p10 <= 55,p17 > 45 AND p9 < 55 AND p2 <= 40 AND p1 > 65 ...,0.061214,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
321,0.689307,remove_90_then,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50,21,p1 >= 60 AND p2 >= 45 AND p3 > 45 AND p4 <= 50...,p10 <= 60 AND p6 > 60 AND p7 <= 50 AND p8 < 60...,0.066421,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
322,0.556161,remove_90_then,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50,22,p1 < 40 AND p2 > 65 AND p3 >= 45 AND p4 >= 55 ...,p10 >= 45 AND p20 >= 45 AND p6 <= 50 AND p7 > ...,0.071896,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
323,0.415501,remove_90_then,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50,23,p18 >= 50 AND p3 < 45 AND p1 > 45 AND p5 > 50 ...,p7 >= 50 AND p13 <= 45 AND p12 <= 50 AND p19 <...,0.075892,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
324,0.392374,remove_90_then,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50,24,p4 < 60 AND p14 <= 65 AND p10 < 45 AND p13 > 5...,p14 >= 60 AND p1 <= 65 AND p9 > 65 AND p10 > 5...,0.059139,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."

In [2]:
df_baseline = df[df['diagnosed_name'] == 'diag_baseline']
df_baseline

import plotly.express as px

fig = px.scatter(
    df_baseline,
    x='candidate_name',           # eixo X: nome do candidato
    y='similarity_result',        # eixo Y: similaridade
    color='similarity_result',    # cor dos pontos pela similaridade
    hover_data=['candidate_given', 'candidate_then'],  # informações extras no hover
    title='Similaridade por Candidato (Diagnosed Baseline)'
)
fig.update_layout(
    xaxis_title='Candidato',
    yaxis_title='Similaridade',
    template='plotly_white'
)
fig.show()

In [3]:
keep_candidates = ["16", "22", "8", "9", "1", "10", "3", "cand_baseline"] # esses sao os que eu mais gostei para visualizar

df = df[df["candidate_name"].astype(str).isin(keep_candidates)]
df

,similarity_result,diagnosed_name,diagnosed_given,diagnosed_then,candidate_name,candidate_given,candidate_then,elapsed_time,config
0,1.000000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.093598,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
1,0.585686,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,1,p1 <= 40 AND p2 >= 55 AND p3 >= 50 AND p4 <= 6...,p10 >= 55 AND p16 > 60 AND p6 < 65 AND p7 <= 5...,0.121454,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
3,0.556667,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,3,p1 < 40 AND p2 > 55 AND p3 < 60 AND p4 > 60 AN...,p10 > 65 AND p6 <= 65 AND p7 < 40 AND p8 > 65 ...,0.095145,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
8,0.679495,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,8,p1 >= 60 AND p2 > 60 AND p3 >= 65 AND p4 < 40 ...,p10 >= 50 AND p6 < 55 AND p7 > 45 AND p8 > 40 ...,0.095333,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
9,0.714676,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,9,p1 >= 55 AND p17 <= 60 AND p2 > 60 AND p3 > 45...,p10 < 55 AND p6 < 60 AND p7 >= 65 AND p8 > 65 ...,0.078292,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
...,...,...,...,...,...,...,...,...,...
308,0.486667,remove_90_then,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50,8,p1 >= 60 AND p2 > 60 AND p3 >= 65 AND p4 < 40 ...,p10 >= 50 AND p6 < 55 AND p7 > 45 AND p8 > 40 ...,0.071335,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
309,0.564676,remove_90_then,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50,9,p1 >= 55 AND p17 <= 60 AND p2 > 60 AND p3 > 45...,p10 < 55 AND p6 < 60 AND p7 >= 65 AND p8 > 65 ...,0.066032,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
310,0.719709,remove_90_then,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50,10,p1 >= 40 AND p3 > 45 AND p5 > 55 AND p17 > 55 ...,p15 > 65 AND p6 > 45 AND p17 > 60 AND p10 > 50,0.060295,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
316,0.552353,remove_90_then,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50,16,p1 > 40 AND p19 <= 65 AND p2 > 65 AND p3 >= 65...,p10 <= 65 AND p6 <= 65 AND p7 >= 55 AND p8 <= ...,0.089352,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
322,0.556161,remove_90_then,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50,22,p1 < 40 AND p2 > 65 AND p3 >= 45 AND p4 >= 55 ...,p10 >= 45 AND p20 >= 45 AND p6 <= 50 AND p7 > ...,0.071896,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."

In [4]:
mapping = {
    "16": 1,
    "22": 2,
    "8":  3,
    "9":  4,
    "1":  5,
    "10": 6,
    "3":  7,
    # "diagnosed_baseline" não entra no mapping para permanecer igual
}

# Garante comparação por string, aplica o mapeamento e preserva o que não estiver no dict
df['candidate_name'] = (
    df['candidate_name'].map(mapping)
                         .fillna(df['candidate_name'])
)

C:\Users\lucas_alves\AppData\Local\Temp\ipykernel_45972\3768853171.py:13: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [5]:
df

,similarity_result,diagnosed_name,diagnosed_given,diagnosed_then,candidate_name,candidate_given,candidate_then,elapsed_time,config
0,1.000000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.093598,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
1,0.585686,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,5.0,p1 <= 40 AND p2 >= 55 AND p3 >= 50 AND p4 <= 6...,p10 >= 55 AND p16 > 60 AND p6 < 65 AND p7 <= 5...,0.121454,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
3,0.556667,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,7.0,p1 < 40 AND p2 > 55 AND p3 < 60 AND p4 > 60 AN...,p10 > 65 AND p6 <= 65 AND p7 < 40 AND p8 > 65 ...,0.095145,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
8,0.679495,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,3.0,p1 >= 60 AND p2 > 60 AND p3 >= 65 AND p4 < 40 ...,p10 >= 50 AND p6 < 55 AND p7 > 45 AND p8 > 40 ...,0.095333,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
9,0.714676,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,4.0,p1 >= 55 AND p17 <= 60 AND p2 > 60 AND p3 > 45...,p10 < 55 AND p6 < 60 AND p7 >= 65 AND p8 > 65 ...,0.078292,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
...,...,...,...,...,...,...,...,...,...
308,0.486667,remove_90_then,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50,3.0,p1 >= 60 AND p2 > 60 AND p3 >= 65 AND p4 < 40 ...,p10 >= 50 AND p6 < 55 AND p7 > 45 AND p8 > 40 ...,0.071335,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
309,0.564676,remove_90_then,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50,4.0,p1 >= 55 AND p17 <= 60 AND p2 > 60 AND p3 > 45...,p10 < 55 AND p6 < 60 AND p7 >= 65 AND p8 > 65 ...,0.066032,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
310,0.719709,remove_90_then,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50,6.0,p1 >= 40 AND p3 > 45 AND p5 > 55 AND p17 > 55 ...,p15 > 65 AND p6 > 45 AND p17 > 60 AND p10 > 50,0.060295,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
316,0.552353,remove_90_then,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50,1.0,p1 > 40 AND p19 <= 65 AND p2 > 65 AND p3 >= 65...,p10 <= 65 AND p6 <= 65 AND p7 >= 55 AND p8 <= ...,0.089352,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
322,0.556161,remove_90_then,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50,2.0,p1 < 40 AND p2 > 65 AND p3 >= 45 AND p4 >= 55 ...,p10 >= 45 AND p20 >= 45 AND p6 <= 50 AND p7 > ...,0.071896,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."

In [6]:
import pandas as pd
import plotly.graph_objects as go

# 3. Ordem das execuções (ajuste conforme necessário)
diagnosis_order = [
    "remove_90_then", "remove_60_then", "remove_30_then", 
    "remove_90_given", "remove_60_given", "remove_30_given", 
    "diag_baseline", 
    "add_30_given", "add_60_given", "add_90_given", 
    "add_30_then", "add_60_then", "add_90_then"
]

# 5. Montar tabela pivô
df_pivot = df.pivot(index="candidate_name", columns="diagnosed_name", values="similarity_result")
df_pivot = df_pivot[[col for col in diagnosis_order if col in df_pivot.columns]]

# 6. Plotar o Slope Chart
fig = go.Figure()
for cand in df_pivot.index:
    fig.add_trace(go.Scatter(
        x=df_pivot.columns,
        y=df_pivot.loc[cand],
        mode='lines+markers',
        name=str(cand)
    ))
fig.update_layout(
    title='Slope Chart - Mudança de Similaridade dos Candidatos Selecionados',
    xaxis_title='Execução Diagnóstica',
    yaxis_title='Similaridade',
    xaxis=dict(tickangle=-45)
)
fig.show()

In [7]:
import pandas as pd
import plotly.graph_objects as go

# Carregar e preparar os dados
diagnosis_order = [
    "remove_90_then", "remove_60_then", "remove_30_then", 
    "remove_90_given", "remove_60_given", "remove_30_given", 
    "diag_baseline", 
    "add_30_given", "add_60_given", "add_90_given", 
    "add_30_then", "add_60_then", "add_90_then"
]

df_pivot = df.pivot(index="candidate_name", columns="diagnosed_name", values="similarity_result")
df_pivot = df_pivot[[col for col in diagnosis_order if col in df_pivot.columns]]

# Gerar o Slope Chart com melhor proporção e destaque visual
fig = go.Figure()
for cand in df_pivot.index:
    fig.add_trace(go.Scatter(
        x=df_pivot.columns,
        y=df_pivot.loc[cand],
        mode='lines+markers+text',
        text=[f'{y:.2f}' for y in df_pivot.loc[cand]],  # Mostra o valor em cada ponto
        textposition="top center",
        name=str(cand),
        line=dict(width=4),
        marker=dict(size=12)
    ))
fig.update_layout(
    title='Slope Chart: Mudança de Similaridade dos Candidatos Selecionados',
    xaxis_title='Execução Diagnóstica',
    yaxis_title='Similaridade',
    xaxis=dict(tickangle=-45),
    width=850,   # largura reduzida
    height=600,  # altura aumentada
    legend=dict(
        title="Candidatos",
        yanchor="top",
        y=0.99,
        xanchor="left",
        x=0.01
    ),
    margin=dict(l=40, r=40, t=70, b=90)
)
fig.show()

In [8]:
import pandas as pd
import plotly.graph_objects as go

# Carregar e preparar os dados
diagnosis_order = [
    "remove_90_then", "remove_60_then", "remove_30_then", 
    "remove_90_given", "remove_60_given", "remove_30_given", 
    "diag_baseline", 
    "add_30_given", "add_60_given", "add_90_given", 
    "add_30_then", "add_60_then", "add_90_then"
]

# Montar matriz pivô
df_pivot = df.pivot(index="candidate_name", columns="diagnosed_name", values="similarity_result")
df_pivot = df_pivot[[col for col in diagnosis_order if col in df_pivot.columns]]

# Gerar ranking (1 = topo) para cada execução
df_rank = df_pivot.rank(ascending=False, axis=0, method='min')

# Plotar o bump chart
fig = go.Figure()
for cand in df_rank.index:
    fig.add_trace(go.Scatter(
        x=df_rank.columns,
        y=df_rank.loc[cand],
        mode='lines+markers+text',
        name=str(cand),
        line=dict(width=4),
        marker=dict(size=13),
        text=["" if i not in [0, len(df_rank.columns)-1] else str(cand) for i in range(len(df_rank.columns))],
        textposition="bottom center"
    ))
fig.update_layout(
    title='Bump Chart - Ranking dos Candidatos ao Longo das Execuções',
    xaxis_title='Execução Diagnóstica',
    yaxis_title='Ranking (1 = topo)',
    yaxis=dict(autorange='reversed', dtick=1),  # 1 no topo!
    xaxis=dict(tickangle=-45),
    width=900,
    height=650,
    legend=dict(title="Candidatos", yanchor="top", y=0.99, xanchor="left", x=0.01),
    margin=dict(l=40, r=40, t=70, b=90)
)
fig.show()

In [9]:
import pandas as pd
import plotly.graph_objects as go

diagnosis_order = [
    "remove_90_then", "remove_60_then", "remove_30_then", 
    "remove_90_given", "remove_60_given", "remove_30_given", 
    "diag_baseline", 
    "add_30_given", "add_60_given", "add_90_given", 
    "add_30_then", "add_60_then", "add_90_then"
]

df_pivot = df.pivot(index="candidate_name", columns="diagnosed_name", values="similarity_result")
df_pivot = df_pivot[[col for col in diagnosis_order if col in df_pivot.columns]]
df_rank = df_pivot.rank(ascending=False, axis=0, method='min')

fig = go.Figure()
for cand in df_rank.index:
    fig.add_trace(go.Scatter(
        x=df_rank.columns,
        y=df_rank.loc[cand],
        mode='lines+markers+text',
        name=str(cand),
        line=dict(width=4),
        marker=dict(size=13),
        text=["" if i not in [0, len(df_rank.columns)-1] else str(cand) for i in range(len(df_rank.columns))],
        textposition="bottom center"
    ))
fig.update_layout(
    title='Bump Chart - Ranking dos Candidatos ao Longo das Execuções',
    xaxis_title='Execução Diagnóstica',
    yaxis_title='Ranking (1 = topo)',
    yaxis=dict(autorange='reversed', dtick=1),
    xaxis=dict(
        tickangle=-45,
        categoryorder='array',
        categoryarray=diagnosis_order,
        tickvals=diagnosis_order,
        ticktext=diagnosis_order
    ),
    width=1500,   # largura aumentada!
    height=700,
    legend=dict(title="Candidatos", yanchor="top", y=0.99, xanchor="left", x=0.01),
    margin=dict(l=40, r=40, t=70, b=90)
)
fig.show()

In [10]:
import pandas as pd
import plotly.graph_objects as go

# Carregar e preparar os dados

diagnosis_order = [
    "remove_90_then", "remove_60_then", "remove_30_then", 
    "remove_90_given", "remove_60_given", "remove_30_given", 
    "diag_baseline", 
    "add_30_given", "add_60_given", "add_90_given", 
    "add_30_then", "add_60_then", "add_90_then"
]

df_pivot = df.pivot(index="candidate_name", columns="diagnosed_name", values="similarity_result")
df_pivot = df_pivot[[col for col in diagnosis_order if col in df_pivot.columns]]
df_rank = df_pivot.rank(ascending=False, axis=0, method='min')

fig = go.Figure()
for cand in df_rank.index:
    similarity_texts = [f"{df_pivot.loc[cand, col]:.2f}" for col in df_pivot.columns]
    fig.add_trace(go.Scatter(
        x=df_rank.columns,
        y=df_rank.loc[cand],
        mode='lines+markers+text',
        name=str(cand),
        line=dict(width=4),
        marker=dict(size=13),
        text=similarity_texts,
        textposition="top center",
        textfont=dict(size=10)  # <<< Ajuste aqui: tamanho do texto!
    ))
fig.update_layout(
    title='Bump Chart - Ranking dos Candidatos ao Longo das Execuções',
    xaxis_title='Execução Diagnóstica',
    yaxis_title='Ranking (1 = topo)',
    yaxis=dict(autorange='reversed', dtick=1),
    xaxis=dict(
        tickangle=-45,
        categoryorder='array',
        categoryarray=diagnosis_order,
        tickvals=diagnosis_order,
        ticktext=diagnosis_order
    ),
    width=1500,
    height=700,
    legend=dict(title="Candidatos", yanchor="top", y=0.99, xanchor="left", x=0.01),
    margin=dict(l=40, r=40, t=70, b=90)
)
fig.show()

In [11]:
import pandas as pd
import plotly.graph_objects as go

diagnosis_order = [
    "remove_90_then", "remove_60_then", "remove_30_then", 
    "remove_90_given", "remove_60_given", "remove_30_given", 
    "diag_baseline", 
    "add_30_given", "add_60_given", "add_90_given", 
    "add_30_then", "add_60_then", "add_90_then"
]

df_pivot = df.pivot(index="candidate_name", columns="diagnosed_name", values="similarity_result")
df_pivot = df_pivot[[col for col in diagnosis_order if col in df_pivot.columns]]
df_rank = df_pivot.rank(ascending=False, axis=0, method='min')

fig = go.Figure()
for cand in df_rank.index:
    similarity_texts = [f"{df_pivot.loc[cand, col]:.2f}" for col in df_pivot.columns]
    fig.add_trace(go.Scatter(
        x=df_rank.columns,
        y=df_rank.loc[cand],
        mode='lines+markers+text',
        name=str(cand),
        line=dict(width=4),
        marker=dict(size=13),
        text=similarity_texts,
        textposition="top center",
        textfont=dict(size=10)
    ))

# Indica a posição central do diagnosed_baseline
baseline_idx = diagnosis_order.index("diag_baseline")

# Adiciona duas linhas tracejadas finas (antes e depois do baseline)
fig.add_vline(
    x=baseline_idx - 0.48,  # um pouco antes
    line_width=1,
    line_dash="dash",
    line_color="black",
    opacity=0.5,
    layer='above'
)
fig.add_vline(
    x=baseline_idx + 0.48,  # um pouco depois
    line_width=1,
    line_dash="dash",
    line_color="black",
    opacity=0.5,
    layer='above'
)

fig.update_layout(
    title='Bump Chart - Ranking dos Candidatos ao Longo das Execuções',
    xaxis_title='Execução Diagnóstica',
    yaxis_title='Ranking (1 = topo)',
    yaxis=dict(autorange='reversed', dtick=1),
    xaxis=dict(
        tickangle=-45,
        categoryorder='array',
        categoryarray=diagnosis_order,
        tickvals=diagnosis_order,
        ticktext=diagnosis_order
    ),
    width=1500,
    height=700,
    legend=dict(title="Candidatos", yanchor="top", y=0.99, xanchor="left", x=0.01),
    margin=dict(l=40, r=40, t=70, b=90)
)
fig.show()

In [12]:
import pandas as pd
import plotly.graph_objects as go

# Carregar e preparar os dados
diagnosis_order = [
    "remove_90_then", "remove_60_then", "remove_30_then", 
    "remove_90_given", "remove_60_given", "remove_30_given", 
    "diag_baseline", 
    "add_30_given", "add_60_given", "add_90_given", 
    "add_30_then", "add_60_then", "add_90_then"
]

# Supondo que seu DataFrame df já está filtrado para os candidatos desejados!
df_pivot = df.pivot(index="candidate_name", columns="diagnosed_name", values="similarity_result")
df_pivot = df_pivot[[col for col in diagnosis_order if col in df_pivot.columns]]
df_rank = df_pivot.rank(ascending=False, axis=0, method='min')

fig = go.Figure()

for cand in df_rank.index:
    similarity_texts = [f"{df_pivot.loc[cand, col]:.2f}" for col in df_pivot.columns]
    fig.add_trace(go.Scatter(
        x=df_rank.columns,
        y=df_rank.loc[cand],
        mode='lines+markers+text',
        name=str(cand),
        line=dict(width=4),
        marker=dict(size=13),
        text=similarity_texts,
        textposition="top center",
        textfont=dict(size=10)
    ))

# Linhas verticais tracejadas finas ao redor do diagnosed_baseline
baseline_idx = diagnosis_order.index("diag_baseline")
fig.add_vline(
    x=baseline_idx - 0.48,
    line_width=1,
    line_dash="dash",
    line_color="black",
    opacity=0.5,
    layer='above'
)
fig.add_vline(
    x=baseline_idx + 0.48,
    line_width=1,
    line_dash="dash",
    line_color="black",
    opacity=0.5,
    layer='above'
)

fig.update_layout(
    title='Bump Chart - Ranking dos Candidatos ao Longo das Execuções',
    xaxis_title='Execução Diagnóstica',
    yaxis_title='Ranking (1 = topo)',
    yaxis=dict(autorange='reversed', dtick=1),
    xaxis=dict(
        tickangle=-45,
        categoryorder='array',
        categoryarray=diagnosis_order,
        tickvals=diagnosis_order,
        ticktext=diagnosis_order
    ),
    width=1500,
    height=700,
    legend=dict(
        title="Candidatos",
        yanchor="top", y=1,
        xanchor="left", x=1.01,      # Legenda à direita, fora do gráfico
        bgcolor="rgba(255,255,255,0.95)",
        bordercolor="#ccc",
        borderwidth=1,
        font=dict(size=13)
    ),
    margin=dict(l=40, r=140, t=70, b=90)  # margem direita maior
)
fig.show()

In [13]:
import pandas as pd
import plotly.graph_objects as go

diagnosis_order = [
    "remove_90_then", "remove_60_then", "remove_30_then", 
    "remove_90_given", "remove_60_given", "remove_30_given", 
    "diag_baseline", 
    "add_30_given", "add_60_given", "add_90_given", 
    "add_30_then", "add_60_then", "add_90_then"
]

# Supondo que seu DataFrame df já está filtrado para os candidatos desejados!
df_pivot = df.pivot(index="candidate_name", columns="diagnosed_name", values="similarity_result")
df_pivot = df_pivot[[col for col in diagnosis_order if col in df_pivot.columns]]
df_rank = df_pivot.rank(ascending=False, axis=0, method='min')

fig = go.Figure()

for cand in df_rank.index:
    similarity_texts = [f"{df_pivot.loc[cand, col]:.2f}" for col in df_pivot.columns]
    fig.add_trace(go.Scatter(
        x=df_rank.columns,
        y=df_rank.loc[cand],
        mode='lines+markers+text',
        name=str(cand),
        line=dict(width=4),
        marker=dict(size=13),
        text=similarity_texts,
        textposition="top center",
        textfont=dict(size=10)
    ))

# Linhas verticais tracejadas finas ao redor do diag_baseline
baseline_idx = diagnosis_order.index("diag_baseline")
fig.add_vline(
    x=baseline_idx - 0.48,
    line_width=1,
    line_dash="dash",
    line_color="black",
    opacity=0.5,
    layer='above'
)
fig.add_vline(
    x=baseline_idx + 0.48,
    line_width=1,
    line_dash="dash",
    line_color="black",
    opacity=0.5,
    layer='above'
)

fig.update_layout(
    title='Bump Chart - Ranking dos Candidatos ao Longo das Execuções',
    xaxis_title='Execução Diagnóstica',
    yaxis_title='Ranking (1 = topo)',
    yaxis=dict(autorange='reversed', dtick=1),
    xaxis=dict(
        tickangle=-45,
        categoryorder='array',
        categoryarray=diagnosis_order,
        tickvals=diagnosis_order,
        ticktext=diagnosis_order
    ),
    width=1000,    # <<< Espaçamento reduzido entre X!
    height=700,
    legend=dict(
        title="Candidatos",
        yanchor="top", y=1,
        xanchor="left", x=1.01,
        bgcolor="rgba(255,255,255,0.95)",
        bordercolor="#ccc",
        borderwidth=1,
        font=dict(size=13)
    ),
    margin=dict(l=40, r=140, t=70, b=90)
)
fig.show()

In [19]:
import pandas as pd
import plotly.graph_objects as go

# Ordem original completa (mantida só para referência)
diagnosis_order = [
    "remove_90_then", "remove_60_then", "remove_30_then",
    "remove_90_given", "remove_60_given", "remove_30_given",
    "diag_baseline",
    "add_30_given", "add_60_given", "add_90_given",
    "add_30_then", "add_60_then", "add_90_then"
]

# 1) Ordem somente com 'given' + baseline (removals → baseline → additions)
given_only_order = [
    "remove_90_given", "remove_60_given", "remove_30_given",
    "diag_baseline",
    "add_30_given", "add_60_given", "add_90_given"
]

# df deve ter colunas: candidate_name, diagnosed_name, similarity_result
df_pivot = df.pivot(index="candidate_name", columns="diagnosed_name", values="similarity_result")

# 2) Seleciona apenas as colunas 'given' + baseline na ordem desejada
given_only_order = [col for col in given_only_order if col in df_pivot.columns]
df_pivot_given = df_pivot[given_only_order]

# 3) Recalcula ranking só para essas execuções
df_rank_given = df_pivot_given.rank(ascending=False, axis=0, method='min')

fig = go.Figure()

for cand in df_rank_given.index:
    similarity_texts = [f"{df_pivot_given.loc[cand, col]:.2f}" for col in df_pivot_given.columns]
    fig.add_trace(go.Scatter(
        x=df_rank_given.columns,
        y=df_rank_given.loc[cand],
        mode='lines+markers+text',
        name=str(cand),
        line=dict(width=4),
        marker=dict(size=13),
        text=similarity_texts,
        textposition="top center",
        textfont=dict(size=10)
    ))

# 4) Linhas verticais tracejadas ao redor do baseline (recalculadas para o novo eixo X)
if "diag_baseline" in given_only_order:
    baseline_idx = given_only_order.index("diag_baseline")
    fig.add_vline(x=baseline_idx - 0.48, line_width=1, line_dash="dash",
                  line_color="black", opacity=0.5, layer='above')
    fig.add_vline(x=baseline_idx + 0.48, line_width=1, line_dash="dash",
                  line_color="black", opacity=0.5, layer='above')

# 5) Layout (legenda horizontal abaixo do eixo X)
fig.update_layout(
    title='Bump Chart — Ranking (only GIVEN perturbations)',
    # xaxis_title='Diagnostic execution',
    yaxis_title='Rank (1 = top)',
    yaxis=dict(autorange='reversed', dtick=1),
    xaxis=dict(
        tickangle=-45,
        categoryorder='array',
        categoryarray=given_only_order,
        tickvals=given_only_order,
        ticktext=given_only_order
    ),
    width=1000,
    height=700,
    legend=dict(
        title="Candidates",
        orientation="h",            # horizontal
        xanchor="center", x=0.5,    # centraliza
        yanchor="top",    y=-0.20,  # posiciona abaixo do eixo X
        bgcolor="rgba(255,255,255,0.95)",
        bordercolor="#ccc",
        borderwidth=1,
        font=dict(size=13)
    ),
    margin=dict(l=40, r=40, t=70, b=160)  # margem inferior maior p/ legenda
)

fig.show()