In [34]:
import pandas as pd
import json

# Caminho para seu arquivo
file_path = 'similarity_results.jsonl'

# Carrega cada linha do arquivo como um dicionário
data = []
with open(file_path, 'r', encoding='utf-8') as f:
    for line in f:
        item = json.loads(line)
        # Extrai campos desejados
        row = {
            'similarity_result': item['similarity_result'],
            'diagnosed_name': item['diagnosed']['name'],
            'diagnosed_given': item['diagnosed']['given'],
            'diagnosed_then': item['diagnosed']['then'],
            'candidate_name': item['candidate']['name'],
            'candidate_given': item['candidate']['given'],
            'candidate_then': item['candidate']['then'],
            'elapsed_time': item['elapsed_time'],
            'config': item['config'],
        }
        data.append(row)

# Cria o DataFrame
df = pd.DataFrame(data)

# Exemplo: mostra as primeiras linhas
df

,similarity_result,diagnosed_name,diagnosed_given,diagnosed_then,candidate_name,candidate_given,candidate_then,elapsed_time,config
0,1.000000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_A1_full_match_all_given_then,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.112551,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '..."
1,0.975000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_B1_error_only_p1_threshold_low,p1 >= 20 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.109252,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '..."
2,0.975000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_C1_error_only_p10_threshold_low,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.093238,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '..."
3,0.975000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_D1_errors_other_params_p2_low_p1_p10_correct,p1 >= 50 AND p2 >= 20 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.096884,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '..."
4,0.950000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_E1_errors_p1_p10_both_threshold_low,p1 >= 20 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.090805,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '..."
5,1.000000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_A1_full_match_all_given_then,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.109869,"{'parameter_weights': {'p1': 1.5, 'p2': 1.0, '..."
6,0.965909,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_B1_error_only_p1_threshold_low,p1 >= 20 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.098096,"{'parameter_weights': {'p1': 1.5, 'p2': 1.0, '..."
7,0.946429,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_C1_error_only_p10_threshold_low,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.128617,"{'parameter_weights': {'p1': 1.5, 'p2': 1.0, '..."
8,0.977273,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_D1_errors_other_params_p2_low_p1_p10_correct,p1 >= 50 AND p2 >= 20 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.103601,"{'parameter_weights': {'p1': 1.5, 'p2': 1.0, '..."
9,0.912338,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_E1_errors_p1_p10_both_threshold_low,p1 >= 20 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.105580,"{'parameter_weights': {'p1': 1.5, 'p2': 1.0, '..."
10,1.000000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_A1_full_match_all_given_then,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.110265,"{'parameter_weights': {'p1': 2.0, 'p2': 1.0, '..."
11,0.958333,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_B1_error_only_p1_threshold_low,p1 >= 20 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.078766,"{'parameter_weights': {'p1': 2.0, 'p2': 1.0, '..."
12,0.937500,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_C1_error_only_p10_threshold_low,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.089262,"{'parameter_weights': {'p1': 2.0, 'p2': 1.0, '..."
13,0.979167,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_D1_errors_other_params_p2_low_p1_p10_correct,p1 >= 50 AND p2 >= 20 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.089753,"{'parameter_weights': {'p1': 2.0, 'p2': 1.0, '..."
14,0.895833,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_E1_errors_p1_p10_both_threshold_low,p1 >= 20 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.096286,"{'parameter_weights': {'p1': 2.0, 'p2': 1.0, '..."
15,1.000000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_A1_full_match_all_given_then,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.089457,"{'parameter_weights': {'p1': 3.0, 'p2': 1.0, '..."
16,0.946429,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_B1_error_only_p1_threshold_low,p1 >= 20 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.072119,"{'parameter_weights': {'p1': 3.0, 'p2': 1.0, '..."
17,0.925000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_C1_error_only_p10_threshold_low,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.080603,"{'parameter_weights': {'p1': 3.0, 'p2': 1.0, '..."
18,0.982143,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_D1_errors_other_params_p2_low_p1_p10_correct,p1 >= 50 AND p2 >= 20 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.069145,"{'parameter_weights': {'p1': 3.0, 'p2': 1.0, '..."
19,0.871429,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_E1_errors_p1_p10_both_threshold_low,p1 >= 20 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.063849,"{'parameter_weights': {'p1': 3.0, 'p2': 1.0, '..."

In [35]:
def extract_cfg_fields(row):
    cfg = row['config']  # já é um dict
    pw = cfg.get('parameter_weights', {})
    tw = cfg.get('tversky_weights', {})
    cw = cfg.get('conditional_weights', {})
    
    return pd.Series({
        'w_p1':    pw.get('p1'),
        'w_p10':   pw.get('p10'),
        'alpha':   tw.get('alpha'),
        'beta':    tw.get('beta'),
        'w_given': cw.get('given'),
        'w_when':  cw.get('when'),
        'w_then':  cw.get('then'),
    })

cfg_cols = df.apply(extract_cfg_fields, axis=1)
df_w = pd.concat([df, cfg_cols], axis=1)
df_w

,similarity_result,diagnosed_name,diagnosed_given,diagnosed_then,candidate_name,candidate_given,candidate_then,elapsed_time,config,w_p1,w_p10,alpha,beta,w_given,w_when,w_then
0,1.000000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_A1_full_match_all_given_then,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.112551,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.9,0.1,1.0,1.0,1.0
1,0.975000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_B1_error_only_p1_threshold_low,p1 >= 20 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.109252,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.9,0.1,1.0,1.0,1.0
2,0.975000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_C1_error_only_p10_threshold_low,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.093238,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.9,0.1,1.0,1.0,1.0
3,0.975000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_D1_errors_other_params_p2_low_p1_p10_correct,p1 >= 50 AND p2 >= 20 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.096884,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.9,0.1,1.0,1.0,1.0
4,0.950000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_E1_errors_p1_p10_both_threshold_low,p1 >= 20 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.090805,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.9,0.1,1.0,1.0,1.0
5,1.000000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_A1_full_match_all_given_then,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.109869,"{'parameter_weights': {'p1': 1.5, 'p2': 1.0, '...",1.5,3.0,0.9,0.1,1.0,1.0,1.0
6,0.965909,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_B1_error_only_p1_threshold_low,p1 >= 20 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.098096,"{'parameter_weights': {'p1': 1.5, 'p2': 1.0, '...",1.5,3.0,0.9,0.1,1.0,1.0,1.0
7,0.946429,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_C1_error_only_p10_threshold_low,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.128617,"{'parameter_weights': {'p1': 1.5, 'p2': 1.0, '...",1.5,3.0,0.9,0.1,1.0,1.0,1.0
8,0.977273,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_D1_errors_other_params_p2_low_p1_p10_correct,p1 >= 50 AND p2 >= 20 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.103601,"{'parameter_weights': {'p1': 1.5, 'p2': 1.0, '...",1.5,3.0,0.9,0.1,1.0,1.0,1.0
9,0.912338,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_E1_errors_p1_p10_both_threshold_low,p1 >= 20 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.105580,"{'parameter_weights': {'p1': 1.5, 'p2': 1.0, '...",1.5,3.0,0.9,0.1,1.0,1.0,1.0
10,1.000000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_A1_full_match_all_given_then,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.110265,"{'parameter_weights': {'p1': 2.0, 'p2': 1.0, '...",2.0,4.0,0.9,0.1,1.0,1.0,1.0
11,0.958333,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_B1_error_only_p1_threshold_low,p1 >= 20 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.078766,"{'parameter_weights': {'p1': 2.0, 'p2': 1.0, '...",2.0,4.0,0.9,0.1,1.0,1.0,1.0
12,0.937500,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_C1_error_only_p10_threshold_low,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.089262,"{'parameter_weights': {'p1': 2.0, 'p2': 1.0, '...",2.0,4.0,0.9,0.1,1.0,1.0,1.0
13,0.979167,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_D1_errors_other_params_p2_low_p1_p10_correct,p1 >= 50 AND p2 >= 20 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.089753,"{'parameter_weights': {'p1': 2.0, 'p2': 1.0, '...",2.0,4.0,0.9,0.1,1.0,1.0,1.0
14,0.895833,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_E1_errors_p1_p10_both_threshold_low,p1 >= 20 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.096286,"{'parameter_weights': {'p1': 2.0, 'p2': 1.0, '...",2.0,4.0,0.9,0.1,1.0,1.0,1.0
15,1.000000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_A1_full_match_all_given_then,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.089457,"{'parameter_weights': {'p1': 3.0, 'p2': 1.0, '...",3.0,6.0,0.9,0.1,1.0,1.0,1.0
16,0.946429,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_B1_error_only_p1_threshold_low,p1 >= 20 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.072119,"{'parameter_weights': {'p1': 3.0, 'p2': 1.0, '...",3.0,6.0,0.9,0.1,1.0,1.0,1.0
17,0.925000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_C1_error_only_p10_threshold_low,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.080603,"{'parameter_weights': {'p1': 3.0, 'p2': 1.0, '...",3.0,6.0,0.9,0.1,1.0,1.0,1.0
18,0.982143,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_D1_errors_other_params_p2_low_p1_p10_correct,p1 >= 50 AND p2 >= 20 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.069145,"{'parameter_weights': {'p1': 3.0, 'p2': 1.0, '...",3.0,6.0,0.9,0.1,1.0,1.0,1.0
19,0.871429,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_E1_errors_p1_p10_both_threshold_low,p1 >= 20 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.063849,"{'parameter_weights': {'p1': 3.0, 'p2': 1.0, '...",3.0,6.0,0.9,0.1,1.0,1.0,1.0

In [41]:
import plotly.express as px

# Mapeia nomes longos para rótulos mais curtos
label_map = {
    "cand_A1_full_match_all_given_then": "Full match",
    "cand_B1_error_only_p1_threshold_low": "p1 low",
    "cand_C1_error_only_p10_threshold_low": "p10 low",
    "cand_D1_errors_other_params_p2_low_p1_p10_correct": "other param low",
    "cand_E1_errors_p1_p10_both_threshold_low": "p1 & p10 low",
}

# 1) ordenar para as linhas ficarem “certinhas”
df_plot = df_w.sort_values(['candidate_name', 'w_p1']).copy()
df_plot["candidate_label"] = df_plot["candidate_name"].map(label_map).fillna(df_plot["candidate_name"])

# 2) gráfico de linhas: uma linha por candidato, x = peso, y = similaridade
fig = px.line(
    df_plot,
    x='w_p1',                      # peso de p1 (e p10)
    y='similarity_result',         # similaridade diagnosed–candidate
    color='candidate_label',       # usa os nomes curtos
    markers=True,
    text=df_plot['similarity_result'].map(lambda v: f"{v:.3f}"),
    labels={
        'w_p1': 'Weight assigned to p1 and p10',
        'similarity_result': 'Similarity',
        'candidate_label': 'Candidate'
    }
)

# 3) colocar os valores de similaridade acima dos pontos
fig.update_traces(textposition='top center')

# valores fixos desejados no eixo X
x_vals   = [1.0, 1.5, 2.0, 3.0]
x_labels = ["(1.0, 1.0)", "(1.5, 3.0)", "(2.0, 4.0)", "(3.0, 6.0)"]

# 4) ajustar eixo X e legenda embaixo, horizontal
fig.update_layout(
    legend_title_text='Candidate:',
    legend=dict(
        orientation='h',
        x=0.5,
        xanchor='center',
        y=-0.25,
        yanchor='top'
    ),
    xaxis=dict(
        tickmode='array',
        tickvals=x_vals,      # posições no eixo (w_p1)
        ticktext=x_labels     # rótulos mostrando (w_p1, w_p10)
    )
)

fig.show()