In [56]:
import pandas as pd
import json

# Caminho para seu arquivo
file_path = 'similarity_results.jsonl'

# Carrega cada linha do arquivo como um dicionário
data = []
with open(file_path, 'r', encoding='utf-8') as f:
    for line in f:
        item = json.loads(line)
        # Extrai campos desejados
        row = {
            'similarity_result': item['similarity_result'],
            'diagnosed_name': item['diagnosed']['name'],
            'diagnosed_given': item['diagnosed']['given'],
            'diagnosed_then': item['diagnosed']['then'],
            'candidate_name': item['candidate']['name'],
            'candidate_given': item['candidate']['given'],
            'candidate_then': item['candidate']['then'],
            'elapsed_time': item['elapsed_time'],
            'config': item['config'],
        }
        data.append(row)

# Cria o DataFrame
df = pd.DataFrame(data)

# Exemplo: mostra as primeiras linhas
df

,similarity_result,diagnosed_name,diagnosed_given,diagnosed_then,candidate_name,candidate_given,candidate_then,elapsed_time,config
0,1.000000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.086507,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '..."
1,0.960000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,high_p1,p1 >= 80 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.078934,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '..."
2,0.975000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,low_p1,p1 >= 20 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.113549,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '..."
3,0.938776,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,without_p1,p2 >= 50 AND p3 >= 50 AND p4 >= 50 AND p5 >= 50,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.101449,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '..."
4,0.960000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,high_p2,p1 >= 50 AND p2 >= 80 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.097889,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '..."
5,0.975000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,low_p2,p1 >= 50 AND p2 >= 20 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.113561,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '..."
6,0.938776,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,without_p2,p1 >= 50 AND p3 >= 50 AND p4 >= 50 AND p5 >= 50,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.088887,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '..."
7,0.993464,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,extra_p12,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.099881,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '..."
8,1.000000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.124802,"{'parameter_weights': {'p1': 2.0, 'p2': 1.0, '..."
9,0.933333,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,high_p1,p1 >= 80 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.126721,"{'parameter_weights': {'p1': 2.0, 'p2': 1.0, '..."
10,0.958333,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,low_p1,p1 >= 20 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.117468,"{'parameter_weights': {'p1': 2.0, 'p2': 1.0, '..."
11,0.938776,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,without_p1,p2 >= 50 AND p3 >= 50 AND p4 >= 50 AND p5 >= 50,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.091191,"{'parameter_weights': {'p1': 2.0, 'p2': 1.0, '..."
12,0.966667,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,high_p2,p1 >= 50 AND p2 >= 80 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.109593,"{'parameter_weights': {'p1': 2.0, 'p2': 1.0, '..."
13,0.979167,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,low_p2,p1 >= 50 AND p2 >= 20 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.089788,"{'parameter_weights': {'p1': 2.0, 'p2': 1.0, '..."
14,0.938776,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,without_p2,p1 >= 50 AND p3 >= 50 AND p4 >= 50 AND p5 >= 50,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.079641,"{'parameter_weights': {'p1': 2.0, 'p2': 1.0, '..."
15,0.993464,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,extra_p12,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.088133,"{'parameter_weights': {'p1': 2.0, 'p2': 1.0, '..."
16,1.000000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.087523,"{'parameter_weights': {'p1': 4.0, 'p2': 1.0, '..."
17,0.900000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,high_p1,p1 >= 80 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.078964,"{'parameter_weights': {'p1': 4.0, 'p2': 1.0, '..."
18,0.937500,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,low_p1,p1 >= 20 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.098002,"{'parameter_weights': {'p1': 4.0, 'p2': 1.0, '..."
19,0.938776,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,without_p1,p2 >= 50 AND p3 >= 50 AND p4 >= 50 AND p5 >= 50,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.092215,"{'parameter_weights': {'p1': 4.0, 'p2': 1.0, '..."
20,0.975000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,high_p2,p1 >= 50 AND p2 >= 80 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.115874,"{'parameter_weights': {'p1': 4.0, 'p2': 1.0, '..."
21,0.984375,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,low_p2,p1 >= 50 AND p2 >= 20 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.085513,"{'parameter_weights': {'p1': 4.0, 'p2': 1.0, '..."
22,0.938776,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,without_p2,p1 >= 50 AND p3 >= 50 AND p4 >= 50 AND p5 >= 50,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.086364,"{'parameter_weights': {'p1': 4.0, 'p2': 1.0, '..."
23,0.993464,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,extra_p12,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.109515,"{'parameter_weights': {'p1': 4.0, 'p2': 1.0, '..."
24,1.000000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.099131,"{'parameter_weights': {'p1': 8.0, 'p2': 1.0, '..."
25,0.866667,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,high_p1,p1 >= 80 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.085094,"{'parameter_weights': {'p1': 8.0, 'p2': 1.0, '..."
26,0.916667,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,low_p1,p1 >= 20 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.089157,"{'parameter_weights': {'p1': 8.0, 'p2': 1.0, '..."
27,0.938776,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,without_p1,p2 >= 50 AND p3 >= 50 AND p4 >= 50 AND p5 >= 50,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.093354,"{'parameter_weights': {'p1': 8.0, 'p2': 1.0, '..."
28,0.983333,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,high_p2,p1 >= 50 AND p2 >= 80 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.082874,"{'parameter_weights': {'p1': 8.0, 'p2': 1.0, '..."
29,0.989583,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,low_p2,p1 >= 50 AND p2 >= 20 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.101443,"{'parameter_weights': {'p1': 8.0, 'p2': 1.0, '..."
30,0.938776,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,without_p2,p1 >= 50 AND p3 >= 50 AND p4 >= 50 AND p5 >= 50,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.079737,"{'parameter_weights': {'p1': 8.0, 'p2': 1.0, '..."
31,0.993464,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,extra_p12,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.061493,"{'parameter_weights': {'p1': 8.0, 'p2': 1.0, '..."

In [57]:
def extract_cfg_fields(row):
    cfg = row['config']  # já é um dict
    pw = cfg.get('parameter_weights', {})
    tw = cfg.get('tversky_weights', {})
    cw = cfg.get('conditional_weights', {})
    
    return pd.Series({
        'w_p1':    pw.get('p1'),
        'w_p10':   pw.get('p10'),
        'alpha':   tw.get('alpha'),
        'beta':    tw.get('beta'),
        'w_given': cw.get('given'),
        'w_when':  cw.get('when'),
        'w_then':  cw.get('then'),
    })

cfg_cols = df.apply(extract_cfg_fields, axis=1)
df_w = pd.concat([df, cfg_cols], axis=1)
df_w

,similarity_result,diagnosed_name,diagnosed_given,diagnosed_then,candidate_name,candidate_given,candidate_then,elapsed_time,config,w_p1,w_p10,alpha,beta,w_given,w_when,w_then
0,1.000000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.086507,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.9,0.1,1.0,1.0,1.0
1,0.960000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,high_p1,p1 >= 80 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.078934,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.9,0.1,1.0,1.0,1.0
2,0.975000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,low_p1,p1 >= 20 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.113549,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.9,0.1,1.0,1.0,1.0
3,0.938776,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,without_p1,p2 >= 50 AND p3 >= 50 AND p4 >= 50 AND p5 >= 50,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.101449,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.9,0.1,1.0,1.0,1.0
4,0.960000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,high_p2,p1 >= 50 AND p2 >= 80 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.097889,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.9,0.1,1.0,1.0,1.0
5,0.975000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,low_p2,p1 >= 50 AND p2 >= 20 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.113561,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.9,0.1,1.0,1.0,1.0
6,0.938776,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,without_p2,p1 >= 50 AND p3 >= 50 AND p4 >= 50 AND p5 >= 50,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.088887,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.9,0.1,1.0,1.0,1.0
7,0.993464,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,extra_p12,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.099881,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.9,0.1,1.0,1.0,1.0
8,1.000000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.124802,"{'parameter_weights': {'p1': 2.0, 'p2': 1.0, '...",2.0,1.0,0.9,0.1,1.0,1.0,1.0
9,0.933333,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,high_p1,p1 >= 80 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.126721,"{'parameter_weights': {'p1': 2.0, 'p2': 1.0, '...",2.0,1.0,0.9,0.1,1.0,1.0,1.0
10,0.958333,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,low_p1,p1 >= 20 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.117468,"{'parameter_weights': {'p1': 2.0, 'p2': 1.0, '...",2.0,1.0,0.9,0.1,1.0,1.0,1.0
11,0.938776,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,without_p1,p2 >= 50 AND p3 >= 50 AND p4 >= 50 AND p5 >= 50,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.091191,"{'parameter_weights': {'p1': 2.0, 'p2': 1.0, '...",2.0,1.0,0.9,0.1,1.0,1.0,1.0
12,0.966667,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,high_p2,p1 >= 50 AND p2 >= 80 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.109593,"{'parameter_weights': {'p1': 2.0, 'p2': 1.0, '...",2.0,1.0,0.9,0.1,1.0,1.0,1.0
13,0.979167,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,low_p2,p1 >= 50 AND p2 >= 20 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.089788,"{'parameter_weights': {'p1': 2.0, 'p2': 1.0, '...",2.0,1.0,0.9,0.1,1.0,1.0,1.0
14,0.938776,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,without_p2,p1 >= 50 AND p3 >= 50 AND p4 >= 50 AND p5 >= 50,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.079641,"{'parameter_weights': {'p1': 2.0, 'p2': 1.0, '...",2.0,1.0,0.9,0.1,1.0,1.0,1.0
15,0.993464,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,extra_p12,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.088133,"{'parameter_weights': {'p1': 2.0, 'p2': 1.0, '...",2.0,1.0,0.9,0.1,1.0,1.0,1.0
16,1.000000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.087523,"{'parameter_weights': {'p1': 4.0, 'p2': 1.0, '...",4.0,1.0,0.9,0.1,1.0,1.0,1.0
17,0.900000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,high_p1,p1 >= 80 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.078964,"{'parameter_weights': {'p1': 4.0, 'p2': 1.0, '...",4.0,1.0,0.9,0.1,1.0,1.0,1.0
18,0.937500,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,low_p1,p1 >= 20 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.098002,"{'parameter_weights': {'p1': 4.0, 'p2': 1.0, '...",4.0,1.0,0.9,0.1,1.0,1.0,1.0
19,0.938776,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,without_p1,p2 >= 50 AND p3 >= 50 AND p4 >= 50 AND p5 >= 50,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.092215,"{'parameter_weights': {'p1': 4.0, 'p2': 1.0, '...",4.0,1.0,0.9,0.1,1.0,1.0,1.0
20,0.975000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,high_p2,p1 >= 50 AND p2 >= 80 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.115874,"{'parameter_weights': {'p1': 4.0, 'p2': 1.0, '...",4.0,1.0,0.9,0.1,1.0,1.0,1.0
21,0.984375,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,low_p2,p1 >= 50 AND p2 >= 20 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.085513,"{'parameter_weights': {'p1': 4.0, 'p2': 1.0, '...",4.0,1.0,0.9,0.1,1.0,1.0,1.0
22,0.938776,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,without_p2,p1 >= 50 AND p3 >= 50 AND p4 >= 50 AND p5 >= 50,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.086364,"{'parameter_weights': {'p1': 4.0, 'p2': 1.0, '...",4.0,1.0,0.9,0.1,1.0,1.0,1.0
23,0.993464,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,extra_p12,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.109515,"{'parameter_weights': {'p1': 4.0, 'p2': 1.0, '...",4.0,1.0,0.9,0.1,1.0,1.0,1.0
24,1.000000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.099131,"{'parameter_weights': {'p1': 8.0, 'p2': 1.0, '...",8.0,1.0,0.9,0.1,1.0,1.0,1.0
25,0.866667,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,high_p1,p1 >= 80 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.085094,"{'parameter_weights': {'p1': 8.0, 'p2': 1.0, '...",8.0,1.0,0.9,0.1,1.0,1.0,1.0
26,0.916667,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,low_p1,p1 >= 20 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.089157,"{'parameter_weights': {'p1': 8.0, 'p2': 1.0, '...",8.0,1.0,0.9,0.1,1.0,1.0,1.0
27,0.938776,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,without_p1,p2 >= 50 AND p3 >= 50 AND p4 >= 50 AND p5 >= 50,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.093354,"{'parameter_weights': {'p1': 8.0, 'p2': 1.0, '...",8.0,1.0,0.9,0.1,1.0,1.0,1.0
28,0.983333,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,high_p2,p1 >= 50 AND p2 >= 80 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.082874,"{'parameter_weights': {'p1': 8.0, 'p2': 1.0, '...",8.0,1.0,0.9,0.1,1.0,1.0,1.0
29,0.989583,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,low_p2,p1 >= 50 AND p2 >= 20 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.101443,"{'parameter_weights': {'p1': 8.0, 'p2': 1.0, '...",8.0,1.0,0.9,0.1,1.0,1.0,1.0
30,0.938776,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,without_p2,p1 >= 50 AND p3 >= 50 AND p4 >= 50 AND p5 >= 50,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.079737,"{'parameter_weights': {'p1': 8.0, 'p2': 1.0, '...",8.0,1.0,0.9,0.1,1.0,1.0,1.0
31,0.993464,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,extra_p12,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.061493,"{'parameter_weights': {'p1': 8.0, 'p2': 1.0, '...",8.0,1.0,0.9,0.1,1.0,1.0,1.0

In [58]:
import plotly.express as px

# Mapeia nomes longos para rótulos mais curtos
label_map = {
    "cand_full_match_all_given_then": "Full match",
    "cand_error_only_p1_threshold_low": "p1 low",
    "cand_error_only_p1_threshold_high": "p1 high",
    "cand_error_only_p10_threshold_low": "p10 low",
    "cand_error_only_p10_threshold_high": "p10 high",
    "cand_errors_other_params_p2_low_p1_p10_correct": "other param low",
    "cand_errors_p1_p10_both_threshold_low": "p1 & p10 low",
    "cand_errors_p1_p10_both_threshold_high": "p1 & p10 high",
    "cand_errors_other_params_p2_high_p1_p10_correct": "other param high",
    "cand_errors_without_p1": "without p1",
    "cand_errors_without_p10": "without p10",
}

# 1) ordenar para as linhas ficarem “certinhas”
df_plot = df_w.sort_values(['candidate_name', 'w_p1']).copy()
df_plot["candidate_label"] = df_plot["candidate_name"].map(label_map).fillna(df_plot["candidate_name"])

# 2) gráfico de linhas: uma linha por candidato, x = peso de p1, y = similaridade
fig = px.line(
    df_plot,
    x='w_p1',
    y='similarity_result',
    color='candidate_label',
    markers=True,
    text=df_plot['similarity_result'].map(lambda v: f"{v:.3f}"),
    labels={
        'w_p1': 'Weight assigned to p1',   # <-- só p1 agora
        'similarity_result': 'Similarity',
        'candidate_label': 'Candidate'
    }
)

# 3) colocar os valores de similaridade acima dos pontos
fig.update_traces(textposition='top center')

# valores fixos desejados no eixo X (só p1 mudou)
x_vals   = [1.0, 2.0, 4.0, 8.0]
x_labels = [f"{v:.1f}" for v in x_vals]   # ou use f"w_p1 = {v:.1f}" se quiser

# 4) ajustar eixo X e legenda embaixo, horizontal
fig.update_layout(
    legend_title_text='Candidate:',
    legend=dict(
        orientation='h',
        x=0.5,
        xanchor='center',
        y=-0.25,
        yanchor='top'
    ),
    xaxis=dict(
        tickmode='array',
        tickvals=x_vals,    # posições no eixo (w_p1)
        ticktext=x_labels   # rótulos mostrando só o peso de p1
    )
)

fig.show()

In [60]:
import plotly.express as px
import pandas as pd


# cria rótulo só com o peso de p1
df_plot["w_p1_str"] = df_plot["w_p1"].map(lambda v: f"{v:.1f}")

# ordem desejada no eixo x (pesos de p1)
ordem_pesos = ["1.0", "2.0", "4.0", "8.0"]
df_plot["w_p1_str"] = pd.Categorical(
    df_plot["w_p1_str"],
    categories=ordem_pesos,
    ordered=True
)

# >>> ordem desejada das ROWS (candidatos)
row_order = [
    "baseline",
    "low_p1",
    "high_p1",
    "low_p2",
    "high_p2",
    "without_p1",
    "without_p2",
    "extra_p12",
]

df_plot["candidate_label"] = pd.Categorical(
    df_plot["candidate_label"],
    categories=row_order,
    ordered=True
)

# pivot: linhas = candidatos, colunas = pesos de p1
heat_df = df_plot.pivot_table(
    index="candidate_label",
    columns="w_p1_str",
    values="similarity_result"
).reindex(row_order)   # garante a ordem das linhas

# heatmap
fig = px.imshow(
    heat_df,
    text_auto=".2f",
    aspect="auto",
    labels={
        "x": "p1 weight",
        "y": "Candidate",
        "color": "Similarity"
    },
    color_continuous_scale="Viridis",
)

fig.update_coloraxes(cmin=0.87, cmax=1.00)

fig.update_layout(
    title=None,
    xaxis_title="p1 weight",
    yaxis_title="Candidate",
    width=700,
    height=400,
    margin=dict(l=120, r=40, t=30, b=60),
    font=dict(size=12)
)

fig.update_xaxes(showgrid=False)
fig.update_yaxes(showgrid=False)

fig.show()

C:\Users\lucas_alves\AppData\Local\Temp\ipykernel_53412\2110004666.py:35: FutureWarning:

The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior