In [2]:
import pandas as pd
import json

# Caminho para seu arquivo
file_path = 'similarity_results.jsonl'

# Carrega cada linha do arquivo como um dicionário
data = []
with open(file_path, 'r', encoding='utf-8') as f:
    for line in f:
        item = json.loads(line)
        # Extrai campos desejados
        row = {
            'similarity_result': item['similarity_result'],
            'diagnosed_name': item['diagnosed']['name'],
            'diagnosed_given': item['diagnosed']['given'],
            'diagnosed_then': item['diagnosed']['then'],
            'candidate_name': item['candidate']['name'],
            'candidate_given': item['candidate']['given'],
            'candidate_then': item['candidate']['then'],
            'elapsed_time': item['elapsed_time'],
            'config': item['config'],
        }
        data.append(row)

# Cria o DataFrame
df = pd.DataFrame(data)

# Exemplo: mostra as primeiras linhas
df

,similarity_result,diagnosed_name,diagnosed_given,diagnosed_then,candidate_name,candidate_given,candidate_then,elapsed_time,config
0,1.000000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.164252,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '..."
1,0.585686,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,1,p1 <= 40 AND p2 >= 55 AND p3 >= 50 AND p4 <= 6...,p10 >= 55 AND p16 > 60 AND p6 < 65 AND p7 <= 5...,0.154616,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '..."
2,0.400000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,2,p4 < 60 AND p8 > 55 AND p1 >= 50 AND p14 <= 40,p14 > 65 AND p17 <= 60 AND p1 > 40 AND p6 >= 5...,0.160617,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '..."
3,0.556667,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,3,p1 < 40 AND p2 > 55 AND p3 < 60 AND p4 > 60 AN...,p10 > 65 AND p6 <= 65 AND p7 < 40 AND p8 > 65 ...,0.197016,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '..."
4,0.430927,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,4,p9 < 65 AND p20 < 50 AND p2 >= 45 AND p16 >= 6...,p3 < 65 AND p16 < 40 AND p8 >= 55 AND p18 >= 4...,0.107093,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '..."
...,...,...,...,...,...,...,...,...,...
95,0.345832,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,20,p7 < 45 AND p18 < 55 AND p12 < 60 AND p10 <= 55,p17 > 45 AND p9 < 55 AND p2 <= 40 AND p1 > 65 ...,0.103320,"{'parameter_weights': {'p1': 3.0, 'p2': 1.0, '..."
96,0.641342,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,21,p1 >= 60 AND p2 >= 45 AND p3 > 45 AND p4 <= 50...,p10 <= 60 AND p6 > 60 AND p7 <= 50 AND p8 < 60...,0.107700,"{'parameter_weights': {'p1': 3.0, 'p2': 1.0, '..."
97,0.703925,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,22,p1 < 40 AND p2 > 65 AND p3 >= 45 AND p4 >= 55 ...,p10 >= 45 AND p20 >= 45 AND p6 <= 50 AND p7 > ...,0.101585,"{'parameter_weights': {'p1': 3.0, 'p2': 1.0, '..."
98,0.463481,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,23,p18 >= 50 AND p3 < 45 AND p1 > 45 AND p5 > 50 ...,p7 >= 50 AND p13 <= 45 AND p12 <= 50 AND p19 <...,0.118854,"{'parameter_weights': {'p1': 3.0, 'p2': 1.0, '..."
99,0.573855,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,24,p4 < 60 AND p14 <= 65 AND p10 < 45 AND p13 > 5...,p14 >= 60 AND p1 <= 65 AND p9 > 65 AND p10 > 5...,0.097628,"{'parameter_weights': {'p1': 3.0, 'p2': 1.0, '..."

In [5]:
def extract_cfg_fields(row):
    cfg = row['config']  # já é um dict
    pw = cfg.get('parameter_weights', {})
    tw = cfg.get('tversky_weights', {})
    cw = cfg.get('conditional_weights', {})
    
    return pd.Series({
        'w_p1':    pw.get('p1'),
        'w_p10':   pw.get('p10'),
        'alpha':   tw.get('alpha'),
        'beta':    tw.get('beta'),
        'w_given': cw.get('given'),
        'w_when':  cw.get('when'),
        'w_then':  cw.get('then'),
    })

cfg_cols = df.apply(extract_cfg_fields, axis=1)
df_w = pd.concat([df, cfg_cols], axis=1)
df_w

,similarity_result,diagnosed_name,diagnosed_given,diagnosed_then,candidate_name,candidate_given,candidate_then,elapsed_time,config,w_p1,w_p10,alpha,beta,w_given,w_when,w_then
0,1.000000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.164252,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.9,0.1,1.0,1.0,1.0
1,0.585686,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,1,p1 <= 40 AND p2 >= 55 AND p3 >= 50 AND p4 <= 6...,p10 >= 55 AND p16 > 60 AND p6 < 65 AND p7 <= 5...,0.154616,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.9,0.1,1.0,1.0,1.0
2,0.400000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,2,p4 < 60 AND p8 > 55 AND p1 >= 50 AND p14 <= 40,p14 > 65 AND p17 <= 60 AND p1 > 40 AND p6 >= 5...,0.160617,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.9,0.1,1.0,1.0,1.0
3,0.556667,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,3,p1 < 40 AND p2 > 55 AND p3 < 60 AND p4 > 60 AN...,p10 > 65 AND p6 <= 65 AND p7 < 40 AND p8 > 65 ...,0.197016,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.9,0.1,1.0,1.0,1.0
4,0.430927,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,4,p9 < 65 AND p20 < 50 AND p2 >= 45 AND p16 >= 6...,p3 < 65 AND p16 < 40 AND p8 >= 55 AND p18 >= 4...,0.107093,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.9,0.1,1.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,0.345832,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,20,p7 < 45 AND p18 < 55 AND p12 < 60 AND p10 <= 55,p17 > 45 AND p9 < 55 AND p2 <= 40 AND p1 > 65 ...,0.103320,"{'parameter_weights': {'p1': 3.0, 'p2': 1.0, '...",3.0,3.0,0.9,0.1,1.0,1.0,1.0
96,0.641342,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,21,p1 >= 60 AND p2 >= 45 AND p3 > 45 AND p4 <= 50...,p10 <= 60 AND p6 > 60 AND p7 <= 50 AND p8 < 60...,0.107700,"{'parameter_weights': {'p1': 3.0, 'p2': 1.0, '...",3.0,3.0,0.9,0.1,1.0,1.0,1.0
97,0.703925,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,22,p1 < 40 AND p2 > 65 AND p3 >= 45 AND p4 >= 55 ...,p10 >= 45 AND p20 >= 45 AND p6 <= 50 AND p7 > ...,0.101585,"{'parameter_weights': {'p1': 3.0, 'p2': 1.0, '...",3.0,3.0,0.9,0.1,1.0,1.0,1.0
98,0.463481,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,23,p18 >= 50 AND p3 < 45 AND p1 > 45 AND p5 > 50 ...,p7 >= 50 AND p13 <= 45 AND p12 <= 50 AND p19 <...,0.118854,"{'parameter_weights': {'p1': 3.0, 'p2': 1.0, '...",3.0,3.0,0.9,0.1,1.0,1.0,1.0
99,0.573855,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,24,p4 < 60 AND p14 <= 65 AND p10 < 45 AND p13 > 5...,p14 >= 60 AND p1 <= 65 AND p9 > 65 AND p10 > 5...,0.097628,"{'parameter_weights': {'p1': 3.0, 'p2': 1.0, '...",3.0,3.0,0.9,0.1,1.0,1.0,1.0

In [7]:
import plotly.express as px
# 2) ordenar para as linhas ficarem “certinhas” (cada candidato em ordem de w_p1)
df_plot = df_w.sort_values(['candidate_name', 'w_p1'])

# 3) gráfico de linhas: uma linha por candidato, x = peso, y = similaridade
fig = px.line(
    df_plot,
    x='w_p1',                 # peso de p1 (e p10)
    y='similarity_result',    # similaridade diagnosed–candidate
    color='candidate_name',   # cada cor/linha = um candidato
    markers=True,
    text=df_plot['similarity_result'].round(2),  # rótulo com a similaridade
    labels={
        'w_p1': 'Weight for p1 (and p10)',
        'similarity_result': 'Similarity (diagnosed vs candidate)',
        'candidate_name': 'Candidate'
    },
    title='Effect of p1/p10 weight on similarity for each candidate'
)

# colocar os valores de similaridade acima dos pontos
fig.update_traces(textposition='top center')

fig.update_layout(
    legend_title_text='Candidate',
    xaxis=dict(
        tickmode='array',
        tickvals=sorted(df_plot['w_p1'].unique()),
        ticktext=[str(v) for v in sorted(df_plot['w_p1'].unique())]
    )
)

fig.show()

In [10]:
import pandas as pd
import plotly.graph_objects as go

diagnosis_order = [
    "diag_90", "diag_75",
    "diag_baseline", 
    "diag_25", "diag_10"
]

# Supondo que seu DataFrame df já está filtrado para os candidatos desejados!
df_pivot = df.pivot(index="candidate_name", columns="diagnosed_name", values="similarity_result")
df_pivot = df_pivot[[col for col in diagnosis_order if col in df_pivot.columns]]
df_rank = df_pivot.rank(ascending=False, axis=0, method='min')

fig = go.Figure()

for cand in df_rank.index:
    similarity_texts = [f"{df_pivot.loc[cand, col]:.2f}" for col in df_pivot.columns]
    fig.add_trace(go.Scatter(
        x=df_rank.columns,
        y=df_rank.loc[cand],
        mode='lines+markers+text',
        name=str(cand),
        line=dict(width=4),
        marker=dict(size=13),
        text=similarity_texts,
        textposition="top center",
        textfont=dict(size=10)
    ))

# Linhas verticais tracejadas finas ao redor do diag_baseline
baseline_idx = diagnosis_order.index("diag_baseline")
fig.add_vline(
    x=baseline_idx - 0.48,
    line_width=1,
    line_dash="dash",
    line_color="black",
    opacity=0.5,
    layer='above'
)
fig.add_vline(
    x=baseline_idx + 0.48,
    line_width=1,
    line_dash="dash",
    line_color="black",
    opacity=0.5,
    layer='above'
)

fig.update_layout(
    title='Bump Chart - Ranking dos Candidatos ao Longo das Execuções',
    # xaxis_title='Execução Diagnóstica',
    # yaxis_title='Ranking (1 = topo)',
    yaxis=dict(autorange='reversed', dtick=1),
    xaxis=dict(
        tickangle=-45,
        categoryorder='array',
        categoryarray=diagnosis_order,
        tickvals=diagnosis_order,
        ticktext=diagnosis_order
    ),
    width=1000,
    height=700,
    legend=dict(
        title="Candidatos",
        orientation="h",          # legenda horizontal
        xanchor="center", x=0.5,  # centraliza
        yanchor="top",    y=-0.20,# posiciona abaixo do eixo X
        bgcolor="rgba(255,255,255,0.95)",
        bordercolor="#ccc",
        borderwidth=1,
        font=dict(size=13)
    ),
    margin=dict(l=40, r=40, t=70, b=160)  # margem inferior maior p/ legenda
)

fig.show()