In [38]:
import pandas as pd
import json

# Caminho para seu arquivo
file_path = 'similarity_results.jsonl'

# Carrega cada linha do arquivo como um dicionário
data = []
with open(file_path, 'r', encoding='utf-8') as f:
    for line in f:
        item = json.loads(line)
        # Extrai campos desejados
        row = {
            'similarity_result': item['similarity_result'],
            'diagnosed_name': item['diagnosed']['name'],
            'diagnosed_given': item['diagnosed']['given'],
            'diagnosed_then': item['diagnosed']['then'],
            'candidate_name': item['candidate']['name'],
            'candidate_given': item['candidate']['given'],
            'candidate_then': item['candidate']['then'],
            'elapsed_time': item['elapsed_time'],
            'config': item['config'],
        }
        data.append(row)

# Cria o DataFrame
df = pd.DataFrame(data)

# Exemplo: mostra as primeiras linhas
df

,similarity_result,diagnosed_name,diagnosed_given,diagnosed_then,candidate_name,candidate_given,candidate_then,elapsed_time,config
0,1.000000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_A_full_match_all_given_then,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.109032,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '..."
1,0.938776,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_B1_missing_p1_given,p2 >= 50 AND p3 >= 50 AND p4 >= 50 AND p5 >= 50,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.136686,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '..."
2,0.875000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_B2_missing_p1_p2_given,p3 >= 50 AND p4 >= 50 AND p5 >= 50,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.093926,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '..."
3,0.993464,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_C1_extra_p12_given,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.102163,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '..."
4,0.987179,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_C2_extra_p12_p13_given,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.176436,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '..."
5,0.933333,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_D1_missing_p1_extra_p12_given,p2 >= 50 AND p3 >= 50 AND p4 >= 50 AND p5 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.102576,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '..."
6,0.866667,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_D2_missing_p1_p2_extra_p12_p13_given,p3 >= 50 AND p4 >= 50 AND p5 >= 50 AND p12 >= ...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.091082,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '..."
7,0.975000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_E_parametric_only_p1_low,p1 >= 20 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.134834,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '..."
8,1.000000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_A_full_match_all_given_then,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.150535,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '..."
9,0.950355,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_B1_missing_p1_given,p2 >= 50 AND p3 >= 50 AND p4 >= 50 AND p5 >= 50,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.174012,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '..."
10,0.893939,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_B2_missing_p1_p2_given,p3 >= 50 AND p4 >= 50 AND p5 >= 50,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.090908,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '..."
11,0.981132,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_C1_extra_p12_given,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.110989,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '..."
12,0.964286,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_C2_extra_p12_p13_given,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.126637,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '..."
13,0.933333,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_D1_missing_p1_extra_p12_given,p2 >= 50 AND p3 >= 50 AND p4 >= 50 AND p5 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.162322,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '..."
14,0.866667,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_D2_missing_p1_p2_extra_p12_p13_given,p3 >= 50 AND p4 >= 50 AND p5 >= 50 AND p12 >= ...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.127630,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '..."
15,0.975000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_E_parametric_only_p1_low,p1 >= 20 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.110935,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '..."
16,1.000000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_A_full_match_all_given_then,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.141721,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '..."
17,0.962963,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_B1_missing_p1_given,p2 >= 50 AND p3 >= 50 AND p4 >= 50 AND p5 >= 50,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.113963,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '..."
18,0.916667,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_B2_missing_p1_p2_given,p3 >= 50 AND p4 >= 50 AND p5 >= 50,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.088284,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '..."
19,0.969697,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_C1_extra_p12_given,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.152134,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '..."
20,0.944444,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_C2_extra_p12_p13_given,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.143535,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '..."
21,0.933333,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_D1_missing_p1_extra_p12_given,p2 >= 50 AND p3 >= 50 AND p4 >= 50 AND p5 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.123767,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '..."
22,0.866667,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_D2_missing_p1_p2_extra_p12_p13_given,p3 >= 50 AND p4 >= 50 AND p5 >= 50 AND p12 >= ...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.116760,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '..."
23,0.975000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_E_parametric_only_p1_low,p1 >= 20 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.124089,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '..."
24,1.000000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_A_full_match_all_given_then,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.113302,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '..."
25,0.976744,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_B1_missing_p1_given,p2 >= 50 AND p3 >= 50 AND p4 >= 50 AND p5 >= 50,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.091724,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '..."
26,0.944444,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_B2_missing_p1_p2_given,p3 >= 50 AND p4 >= 50 AND p5 >= 50,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.117828,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '..."
27,0.959064,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_C1_extra_p12_given,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.106496,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '..."
28,0.927083,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_C2_extra_p12_p13_given,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.152908,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '..."
29,0.933333,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_D1_missing_p1_extra_p12_given,p2 >= 50 AND p3 >= 50 AND p4 >= 50 AND p5 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.165283,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '..."
30,0.866667,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_D2_missing_p1_p2_extra_p12_p13_given,p3 >= 50 AND p4 >= 50 AND p5 >= 50 AND p12 >= ...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.143729,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '..."
31,0.975000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_E_parametric_only_p1_low,p1 >= 20 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.090264,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '..."
32,1.000000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_A_full_match_all_given_then,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.105601,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '..."
33,0.991870,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_B1_missing_p1_given,p2 >= 50 AND p3 >= 50 AND p4 >= 50 AND p5 >= 50,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.081874,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '..."
34,0.979167,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_B2_missing_p1_p2_given,p3 >= 50 AND p4 >= 50 AND p5 >= 50,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.111352,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '..."
35,0.949153,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_C1_extra_p12_given,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.094648,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '..."
36,0.911765,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_C2_extra_p12_p13_given,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.111759,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '..."
37,0.933333,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_D1_missing_p1_extra_p12_given,p2 >= 50 AND p3 >= 50 AND p4 >= 50 AND p5 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.111946,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '..."
38,0.866667,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_D2_missing_p1_p2_extra_p12_p13_given,p3 >= 50 AND p4 >= 50 AND p5 >= 50 AND p12 >= ...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.089093,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '..."
39,0.975000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_E_parametric_only_p1_low,p1 >= 20 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.104868,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '..."

In [39]:
def extract_cfg_fields(row):
    cfg = row['config']  # já é um dict
    pw = cfg.get('parameter_weights', {})
    tw = cfg.get('tversky_weights', {})
    cw = cfg.get('conditional_weights', {})
    
    return pd.Series({
        'w_p1':    pw.get('p1'),
        'w_p10':   pw.get('p10'),
        'alpha':   tw.get('alpha'),
        'beta':    tw.get('beta'),
        'w_given': cw.get('given'),
        'w_when':  cw.get('when'),
        'w_then':  cw.get('then'),
    })

cfg_cols = df.apply(extract_cfg_fields, axis=1)
df_w = pd.concat([df, cfg_cols], axis=1)
df_w

,similarity_result,diagnosed_name,diagnosed_given,diagnosed_then,candidate_name,candidate_given,candidate_then,elapsed_time,config,w_p1,w_p10,alpha,beta,w_given,w_when,w_then
0,1.000000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_A_full_match_all_given_then,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.109032,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.9,0.1,1.0,1.0,1.0
1,0.938776,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_B1_missing_p1_given,p2 >= 50 AND p3 >= 50 AND p4 >= 50 AND p5 >= 50,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.136686,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.9,0.1,1.0,1.0,1.0
2,0.875000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_B2_missing_p1_p2_given,p3 >= 50 AND p4 >= 50 AND p5 >= 50,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.093926,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.9,0.1,1.0,1.0,1.0
3,0.993464,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_C1_extra_p12_given,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.102163,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.9,0.1,1.0,1.0,1.0
4,0.987179,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_C2_extra_p12_p13_given,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.176436,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.9,0.1,1.0,1.0,1.0
5,0.933333,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_D1_missing_p1_extra_p12_given,p2 >= 50 AND p3 >= 50 AND p4 >= 50 AND p5 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.102576,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.9,0.1,1.0,1.0,1.0
6,0.866667,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_D2_missing_p1_p2_extra_p12_p13_given,p3 >= 50 AND p4 >= 50 AND p5 >= 50 AND p12 >= ...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.091082,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.9,0.1,1.0,1.0,1.0
7,0.975000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_E_parametric_only_p1_low,p1 >= 20 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.134834,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.9,0.1,1.0,1.0,1.0
8,1.000000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_A_full_match_all_given_then,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.150535,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.7,0.3,1.0,1.0,1.0
9,0.950355,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_B1_missing_p1_given,p2 >= 50 AND p3 >= 50 AND p4 >= 50 AND p5 >= 50,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.174012,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.7,0.3,1.0,1.0,1.0
10,0.893939,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_B2_missing_p1_p2_given,p3 >= 50 AND p4 >= 50 AND p5 >= 50,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.090908,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.7,0.3,1.0,1.0,1.0
11,0.981132,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_C1_extra_p12_given,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.110989,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.7,0.3,1.0,1.0,1.0
12,0.964286,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_C2_extra_p12_p13_given,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.126637,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.7,0.3,1.0,1.0,1.0
13,0.933333,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_D1_missing_p1_extra_p12_given,p2 >= 50 AND p3 >= 50 AND p4 >= 50 AND p5 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.162322,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.7,0.3,1.0,1.0,1.0
14,0.866667,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_D2_missing_p1_p2_extra_p12_p13_given,p3 >= 50 AND p4 >= 50 AND p5 >= 50 AND p12 >= ...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.127630,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.7,0.3,1.0,1.0,1.0
15,0.975000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_E_parametric_only_p1_low,p1 >= 20 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.110935,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.7,0.3,1.0,1.0,1.0
16,1.000000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_A_full_match_all_given_then,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.141721,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.5,0.5,1.0,1.0,1.0
17,0.962963,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_B1_missing_p1_given,p2 >= 50 AND p3 >= 50 AND p4 >= 50 AND p5 >= 50,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.113963,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.5,0.5,1.0,1.0,1.0
18,0.916667,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_B2_missing_p1_p2_given,p3 >= 50 AND p4 >= 50 AND p5 >= 50,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.088284,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.5,0.5,1.0,1.0,1.0
19,0.969697,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_C1_extra_p12_given,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.152134,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.5,0.5,1.0,1.0,1.0
20,0.944444,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_C2_extra_p12_p13_given,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.143535,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.5,0.5,1.0,1.0,1.0
21,0.933333,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_D1_missing_p1_extra_p12_given,p2 >= 50 AND p3 >= 50 AND p4 >= 50 AND p5 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.123767,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.5,0.5,1.0,1.0,1.0
22,0.866667,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_D2_missing_p1_p2_extra_p12_p13_given,p3 >= 50 AND p4 >= 50 AND p5 >= 50 AND p12 >= ...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.116760,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.5,0.5,1.0,1.0,1.0
23,0.975000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_E_parametric_only_p1_low,p1 >= 20 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.124089,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.5,0.5,1.0,1.0,1.0
24,1.000000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_A_full_match_all_given_then,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.113302,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.3,0.7,1.0,1.0,1.0
25,0.976744,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_B1_missing_p1_given,p2 >= 50 AND p3 >= 50 AND p4 >= 50 AND p5 >= 50,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.091724,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.3,0.7,1.0,1.0,1.0
26,0.944444,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_B2_missing_p1_p2_given,p3 >= 50 AND p4 >= 50 AND p5 >= 50,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.117828,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.3,0.7,1.0,1.0,1.0
27,0.959064,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_C1_extra_p12_given,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.106496,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.3,0.7,1.0,1.0,1.0
28,0.927083,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_C2_extra_p12_p13_given,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.152908,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.3,0.7,1.0,1.0,1.0
29,0.933333,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_D1_missing_p1_extra_p12_given,p2 >= 50 AND p3 >= 50 AND p4 >= 50 AND p5 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.165283,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.3,0.7,1.0,1.0,1.0
30,0.866667,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_D2_missing_p1_p2_extra_p12_p13_given,p3 >= 50 AND p4 >= 50 AND p5 >= 50 AND p12 >= ...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.143729,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.3,0.7,1.0,1.0,1.0
31,0.975000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_E_parametric_only_p1_low,p1 >= 20 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.090264,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.3,0.7,1.0,1.0,1.0
32,1.000000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_A_full_match_all_given_then,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.105601,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.1,0.9,1.0,1.0,1.0
33,0.991870,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_B1_missing_p1_given,p2 >= 50 AND p3 >= 50 AND p4 >= 50 AND p5 >= 50,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.081874,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.1,0.9,1.0,1.0,1.0
34,0.979167,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_B2_missing_p1_p2_given,p3 >= 50 AND p4 >= 50 AND p5 >= 50,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.111352,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.1,0.9,1.0,1.0,1.0
35,0.949153,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_C1_extra_p12_given,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.094648,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.1,0.9,1.0,1.0,1.0
36,0.911765,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_C2_extra_p12_p13_given,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.111759,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.1,0.9,1.0,1.0,1.0
37,0.933333,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_D1_missing_p1_extra_p12_given,p2 >= 50 AND p3 >= 50 AND p4 >= 50 AND p5 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.111946,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.1,0.9,1.0,1.0,1.0
38,0.866667,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_D2_missing_p1_p2_extra_p12_p13_given,p3 >= 50 AND p4 >= 50 AND p5 >= 50 AND p12 >= ...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.089093,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.1,0.9,1.0,1.0,1.0
39,0.975000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_E_parametric_only_p1_low,p1 >= 20 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.104868,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.1,0.9,1.0,1.0,1.0

In [40]:
df_w

,similarity_result,diagnosed_name,diagnosed_given,diagnosed_then,candidate_name,candidate_given,candidate_then,elapsed_time,config,w_p1,w_p10,alpha,beta,w_given,w_when,w_then
0,1.000000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_A_full_match_all_given_then,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.109032,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.9,0.1,1.0,1.0,1.0
1,0.938776,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_B1_missing_p1_given,p2 >= 50 AND p3 >= 50 AND p4 >= 50 AND p5 >= 50,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.136686,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.9,0.1,1.0,1.0,1.0
2,0.875000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_B2_missing_p1_p2_given,p3 >= 50 AND p4 >= 50 AND p5 >= 50,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.093926,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.9,0.1,1.0,1.0,1.0
3,0.993464,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_C1_extra_p12_given,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.102163,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.9,0.1,1.0,1.0,1.0
4,0.987179,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_C2_extra_p12_p13_given,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.176436,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.9,0.1,1.0,1.0,1.0
5,0.933333,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_D1_missing_p1_extra_p12_given,p2 >= 50 AND p3 >= 50 AND p4 >= 50 AND p5 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.102576,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.9,0.1,1.0,1.0,1.0
6,0.866667,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_D2_missing_p1_p2_extra_p12_p13_given,p3 >= 50 AND p4 >= 50 AND p5 >= 50 AND p12 >= ...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.091082,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.9,0.1,1.0,1.0,1.0
7,0.975000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_E_parametric_only_p1_low,p1 >= 20 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.134834,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.9,0.1,1.0,1.0,1.0
8,1.000000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_A_full_match_all_given_then,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.150535,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.7,0.3,1.0,1.0,1.0
9,0.950355,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_B1_missing_p1_given,p2 >= 50 AND p3 >= 50 AND p4 >= 50 AND p5 >= 50,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.174012,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.7,0.3,1.0,1.0,1.0
10,0.893939,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_B2_missing_p1_p2_given,p3 >= 50 AND p4 >= 50 AND p5 >= 50,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.090908,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.7,0.3,1.0,1.0,1.0
11,0.981132,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_C1_extra_p12_given,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.110989,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.7,0.3,1.0,1.0,1.0
12,0.964286,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_C2_extra_p12_p13_given,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.126637,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.7,0.3,1.0,1.0,1.0
13,0.933333,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_D1_missing_p1_extra_p12_given,p2 >= 50 AND p3 >= 50 AND p4 >= 50 AND p5 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.162322,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.7,0.3,1.0,1.0,1.0
14,0.866667,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_D2_missing_p1_p2_extra_p12_p13_given,p3 >= 50 AND p4 >= 50 AND p5 >= 50 AND p12 >= ...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.127630,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.7,0.3,1.0,1.0,1.0
15,0.975000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_E_parametric_only_p1_low,p1 >= 20 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.110935,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.7,0.3,1.0,1.0,1.0
16,1.000000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_A_full_match_all_given_then,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.141721,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.5,0.5,1.0,1.0,1.0
17,0.962963,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_B1_missing_p1_given,p2 >= 50 AND p3 >= 50 AND p4 >= 50 AND p5 >= 50,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.113963,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.5,0.5,1.0,1.0,1.0
18,0.916667,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_B2_missing_p1_p2_given,p3 >= 50 AND p4 >= 50 AND p5 >= 50,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.088284,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.5,0.5,1.0,1.0,1.0
19,0.969697,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_C1_extra_p12_given,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.152134,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.5,0.5,1.0,1.0,1.0
20,0.944444,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_C2_extra_p12_p13_given,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.143535,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.5,0.5,1.0,1.0,1.0
21,0.933333,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_D1_missing_p1_extra_p12_given,p2 >= 50 AND p3 >= 50 AND p4 >= 50 AND p5 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.123767,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.5,0.5,1.0,1.0,1.0
22,0.866667,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_D2_missing_p1_p2_extra_p12_p13_given,p3 >= 50 AND p4 >= 50 AND p5 >= 50 AND p12 >= ...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.116760,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.5,0.5,1.0,1.0,1.0
23,0.975000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_E_parametric_only_p1_low,p1 >= 20 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.124089,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.5,0.5,1.0,1.0,1.0
24,1.000000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_A_full_match_all_given_then,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.113302,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.3,0.7,1.0,1.0,1.0
25,0.976744,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_B1_missing_p1_given,p2 >= 50 AND p3 >= 50 AND p4 >= 50 AND p5 >= 50,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.091724,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.3,0.7,1.0,1.0,1.0
26,0.944444,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_B2_missing_p1_p2_given,p3 >= 50 AND p4 >= 50 AND p5 >= 50,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.117828,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.3,0.7,1.0,1.0,1.0
27,0.959064,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_C1_extra_p12_given,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.106496,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.3,0.7,1.0,1.0,1.0
28,0.927083,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_C2_extra_p12_p13_given,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.152908,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.3,0.7,1.0,1.0,1.0
29,0.933333,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_D1_missing_p1_extra_p12_given,p2 >= 50 AND p3 >= 50 AND p4 >= 50 AND p5 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.165283,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.3,0.7,1.0,1.0,1.0
30,0.866667,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_D2_missing_p1_p2_extra_p12_p13_given,p3 >= 50 AND p4 >= 50 AND p5 >= 50 AND p12 >= ...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.143729,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.3,0.7,1.0,1.0,1.0
31,0.975000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_E_parametric_only_p1_low,p1 >= 20 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.090264,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.3,0.7,1.0,1.0,1.0
32,1.000000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_A_full_match_all_given_then,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.105601,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.1,0.9,1.0,1.0,1.0
33,0.991870,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_B1_missing_p1_given,p2 >= 50 AND p3 >= 50 AND p4 >= 50 AND p5 >= 50,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.081874,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.1,0.9,1.0,1.0,1.0
34,0.979167,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_B2_missing_p1_p2_given,p3 >= 50 AND p4 >= 50 AND p5 >= 50,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.111352,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.1,0.9,1.0,1.0,1.0
35,0.949153,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_C1_extra_p12_given,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.094648,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.1,0.9,1.0,1.0,1.0
36,0.911765,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_C2_extra_p12_p13_given,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.111759,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.1,0.9,1.0,1.0,1.0
37,0.933333,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_D1_missing_p1_extra_p12_given,p2 >= 50 AND p3 >= 50 AND p4 >= 50 AND p5 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.111946,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.1,0.9,1.0,1.0,1.0
38,0.866667,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_D2_missing_p1_p2_extra_p12_p13_given,p3 >= 50 AND p4 >= 50 AND p5 >= 50 AND p12 >= ...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.089093,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.1,0.9,1.0,1.0,1.0
39,0.975000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_E_parametric_only_p1_low,p1 >= 20 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.104868,"{'parameter_weights': {'p1': 1.0, 'p2': 1.0, '...",1.0,1.0,0.1,0.9,1.0,1.0,1.0

In [44]:
import plotly.express as px
import pandas as pd

df_plot = df_w.copy()

# 1) Mapeia nomes internos -> labels técnicos
label_map = {
    "cand_A_full_match_all_given_then": "baseline",
    "cand_B1_missing_p1_given": "missing-p1",
    "cand_B2_missing_p1_p2_given": "missing-p1p2",
    "cand_C1_extra_p12_given": "extra-p12",
    "cand_C2_extra_p12_p13_given": "extra-p12p13",
    "cand_D1_missing_p1_extra_p12_given": "missing-p1+extra-p12",
    "cand_D2_missing_p1_p2_extra_p12_p13_given": "missing-p1p2+extra-p12p13",
    "cand_E_parametric_only_p1_low": "param-p1-low",
}

df_plot["candidate_label"] = df_plot["candidate_name"].map(label_map)

# (opcional) define ordem dos candidatos no eixo Y
candidate_order = [
    "baseline",
    "missing-p1",
    "missing-p1p2",
    "extra-p12",
    "extra-p12p13",
    "missing-p1+extra-p12",
    "missing-p1p2+extra-p12p13",
    "param-p1-low",
]
df_plot["candidate_label"] = pd.Categorical(
    df_plot["candidate_label"],
    categories=candidate_order,
    ordered=True
)

# 2) cria rótulo da configuração (α, β)
df_plot["alpha_beta"] = df_plot.apply(
    lambda r: f"(α={r['alpha']:.1f}, β={r['beta']:.1f})",
    axis=1
)

config_order = sorted(df_plot["alpha_beta"].unique())
df_plot["alpha_beta"] = pd.Categorical(
    df_plot["alpha_beta"],
    categories=config_order,
    ordered=True
)

# 3) pivot: linhas = candidato (label), colunas = configuração
heat_df = df_plot.pivot_table(
    index="candidate_label",
    columns="alpha_beta",
    values="similarity_result"
)

fig = px.imshow(
    heat_df,
    text_auto=".2f",
    aspect="auto",
    labels={
        "x": "Penalty configuration (α, β)",
        "y": "Candidate",
        "color": "Similarity"
    },
    color_continuous_scale="Viridis"
)

fig.update_coloraxes(
    cmin=df_plot["similarity_result"].min(),
    cmax=df_plot["similarity_result"].max()
)

fig.update_layout(
    title=None,
    width=800,
    height=400,
    margin=dict(l=140, r=40, t=30, b=80),
    font=dict(size=12),
    xaxis=dict(tickangle=-10)
)

fig.update_xaxes(showgrid=False)
fig.update_yaxes(showgrid=False)

fig.show()

C:\Users\lucas_alves\AppData\Local\Temp\ipykernel_35640\3529672470.py:51: FutureWarning:

The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior

In [42]:
import plotly.express as px
import pandas as pd

# rótulo legível para cada regime de pesos
df_plot = df_w.copy()
df_plot["penalty_regime"] = df_plot.apply(
    lambda r: f"T(α={r['alpha']:.1f}, β={r['beta']:.1f})",
    axis=1
)

regime_order = sorted(df_plot["penalty_regime"].unique())
df_plot["penalty_regime"] = pd.Categorical(
    df_plot["penalty_regime"],
    categories=regime_order,
    ordered=True
)

fig = px.line(
    df_plot,
    x="penalty_regime",
    y="similarity_result",
    color="candidate_name",
    markers=True,
    labels={
        "penalty_regime": "Penalty regime (α, β)",
        "similarity_result": "Similarity",
        "candidate_name": "Candidate"
    }
)

fig.update_traces(mode="lines+markers")

fig.update_layout(
    width=900,
    height=400,
    margin=dict(l=60, r=20, t=30, b=80),
    xaxis_tickangle=-30
)

fig.show()

In [43]:
import plotly.express as px

fig = px.box(
    df_w,
    x="candidate_name",
    y="similarity_result",
    points="all",
    labels={
        "candidate_name": "Candidate",
        "similarity_result": "Similarity"
    }
)

fig.update_layout(
    width=900,
    height=400,
    margin=dict(l=60, r=40, t=30, b=80),
    xaxis_tickangle=-30
)

fig.show()