In [1]:
import pandas as pd
import json

# Caminho para seu arquivo
file_path = 'similarity_results.jsonl'

# Carrega cada linha do arquivo como um dicionário
data = []
with open(file_path, 'r', encoding='utf-8') as f:
    for line in f:
        item = json.loads(line)
        # Extrai campos desejados
        row = {
            'similarity_result': item['similarity_result'],
            'diagnosed_name': item['diagnosed']['name'],
            'diagnosed_given': item['diagnosed']['given'],
            'diagnosed_then': item['diagnosed']['then'],
            'candidate_name': item['candidate']['name'],
            'candidate_given': item['candidate']['given'],
            'candidate_then': item['candidate']['then'],
            'elapsed_time': item['elapsed_time'],
            'config': item['config'],
        }
        data.append(row)

# Cria o DataFrame
df = pd.DataFrame(data)

# Exemplo: mostra as primeiras linhas
df

,similarity_result,diagnosed_name,diagnosed_given,diagnosed_then,candidate_name,candidate_given,candidate_then,elapsed_time,config
0,1.000000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.105050,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
1,0.585686,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,1,p1 <= 40 AND p2 >= 55 AND p3 >= 50 AND p4 <= 6...,p10 >= 55 AND p16 > 60 AND p6 < 65 AND p7 <= 5...,0.116186,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
2,0.400000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,2,p4 < 60 AND p8 > 55 AND p1 >= 50 AND p14 <= 40,p14 > 65 AND p17 <= 60 AND p1 > 40 AND p6 >= 5...,0.099532,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
3,0.556667,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,3,p1 < 40 AND p2 > 55 AND p3 < 60 AND p4 > 60 AN...,p10 > 65 AND p6 <= 65 AND p7 < 40 AND p8 > 65 ...,0.120701,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
4,0.430927,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,4,p9 < 65 AND p20 < 50 AND p2 >= 45 AND p16 >= 6...,p3 < 65 AND p16 < 40 AND p8 >= 55 AND p18 >= 4...,0.105272,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
...,...,...,...,...,...,...,...,...,...
120,0.333333,diag_10,p1 >= 10 AND p2 >= 10 AND p3 >= 10 AND p4 >= 1...,p6 >= 10 AND p7 >= 10 AND p8 >= 10 AND p9 >= 1...,20,p7 < 45 AND p18 < 55 AND p12 < 60 AND p10 <= 55,p17 > 45 AND p9 < 55 AND p2 <= 40 AND p1 > 65 ...,0.072873,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
121,0.664073,diag_10,p1 >= 10 AND p2 >= 10 AND p3 >= 10 AND p4 >= 1...,p6 >= 10 AND p7 >= 10 AND p8 >= 10 AND p9 >= 1...,21,p1 >= 60 AND p2 >= 45 AND p3 > 45 AND p4 <= 50...,p10 <= 60 AND p6 > 60 AND p7 <= 50 AND p8 < 60...,0.088275,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
122,0.658279,diag_10,p1 >= 10 AND p2 >= 10 AND p3 >= 10 AND p4 >= 1...,p6 >= 10 AND p7 >= 10 AND p8 >= 10 AND p9 >= 1...,22,p1 < 40 AND p2 > 65 AND p3 >= 45 AND p4 >= 55 ...,p10 >= 45 AND p20 >= 45 AND p6 <= 50 AND p7 > ...,0.093248,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
123,0.420940,diag_10,p1 >= 10 AND p2 >= 10 AND p3 >= 10 AND p4 >= 1...,p6 >= 10 AND p7 >= 10 AND p8 >= 10 AND p9 >= 1...,23,p18 >= 50 AND p3 < 45 AND p1 > 45 AND p5 > 50 ...,p7 >= 50 AND p13 <= 45 AND p12 <= 50 AND p19 <...,0.096971,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
124,0.439290,diag_10,p1 >= 10 AND p2 >= 10 AND p3 >= 10 AND p4 >= 1...,p6 >= 10 AND p7 >= 10 AND p8 >= 10 AND p9 >= 1...,24,p4 < 60 AND p14 <= 65 AND p10 < 45 AND p13 > 5...,p14 >= 60 AND p1 <= 65 AND p9 > 65 AND p10 > 5...,0.075885,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."

In [2]:
df_baseline = df[df['diagnosed_name'] == 'diag_baseline']
df_baseline

import plotly.express as px

fig = px.scatter(
    df_baseline,
    x='candidate_name',           # eixo X: nome do candidato
    y='similarity_result',        # eixo Y: similaridade
    color='similarity_result',    # cor dos pontos pela similaridade
    hover_data=['candidate_given', 'candidate_then'],  # informações extras no hover
    title='Similaridade por Candidato (Diagnosed Baseline)'
)
fig.update_layout(
    xaxis_title='Candidato',
    yaxis_title='Similaridade',
    template='plotly_white'
)
fig.show()

In [3]:
keep_candidates = ["6", "7", "12", "15", "18", "19", "5", "cand_baseline"] # esses sao os que eu mais gostei para visualizar

df = df[df["candidate_name"].astype(str).isin(keep_candidates)]
df

,similarity_result,diagnosed_name,diagnosed_given,diagnosed_then,candidate_name,candidate_given,candidate_then,elapsed_time,config
0,1.000000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.105050,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
5,0.751817,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,5,p1 >= 45 AND p2 < 65 AND p3 >= 55 AND p4 >= 40...,p10 < 45 AND p6 <= 50 AND p7 >= 40 AND p8 >= 4...,0.109494,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
6,0.906797,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,6,p1 >= 55 AND p18 >= 55 AND p2 >= 60 AND p3 >= ...,p10 >= 60 AND p6 >= 60 AND p7 >= 55 AND p8 >= ...,0.136965,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
7,0.946797,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,7,p1 >= 50 AND p2 >= 50 AND p20 >= 60 AND p3 >= ...,p10 >= 50 AND p6 >= 50 AND p7 >= 60 AND p8 >= ...,0.111955,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
12,0.900131,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,12,p1 >= 60 AND p2 >= 60 AND p3 >= 60 AND p4 >= 6...,p10 >= 55 AND p16 >= 60 AND p6 >= 60 AND p7 >=...,0.112124,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
15,0.840131,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,15,p1 >= 55 AND p13 >= 50 AND p2 >= 60 AND p3 >= ...,p10 >= 55 AND p16 >= 60 AND p7 >= 55 AND p8 >=...,0.180782,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
18,0.873464,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,18,p1 >= 50 AND p19 >= 50 AND p3 >= 55 AND p4 >= ...,p10 >= 60 AND p18 >= 55 AND p6 >= 50 AND p7 >=...,0.152935,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
19,0.802828,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,19,p1 > 40 AND p2 > 65 AND p3 >= 65 AND p4 > 50 A...,p10 > 45 AND p6 > 50 AND p7 >= 55 AND p8 <= 55...,0.131406,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
25,0.466667,diag_90,p1 >= 90 AND p2 >= 90 AND p3 >= 90 AND p4 >= 9...,p6 >= 90 AND p7 >= 90 AND p8 >= 90 AND p9 >= 9...,cand_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.120358,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
30,0.417846,diag_90,p1 >= 90 AND p2 >= 90 AND p3 >= 90 AND p4 >= 9...,p6 >= 90 AND p7 >= 90 AND p8 >= 90 AND p9 >= 9...,5,p1 >= 45 AND p2 < 65 AND p3 >= 55 AND p4 >= 40...,p10 < 45 AND p6 <= 50 AND p7 >= 40 AND p8 >= 4...,0.102087,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
31,0.481241,diag_90,p1 >= 90 AND p2 >= 90 AND p3 >= 90 AND p4 >= 9...,p6 >= 90 AND p7 >= 90 AND p8 >= 90 AND p9 >= 9...,6,p1 >= 55 AND p18 >= 55 AND p2 >= 60 AND p3 >= ...,p10 >= 60 AND p6 >= 60 AND p7 >= 55 AND p8 >= ...,0.091496,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
32,0.471241,diag_90,p1 >= 90 AND p2 >= 90 AND p3 >= 90 AND p4 >= 9...,p6 >= 90 AND p7 >= 90 AND p8 >= 90 AND p9 >= 9...,7,p1 >= 50 AND p2 >= 50 AND p20 >= 60 AND p3 >= ...,p10 >= 50 AND p6 >= 50 AND p7 >= 60 AND p8 >= ...,0.132202,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
37,0.483093,diag_90,p1 >= 90 AND p2 >= 90 AND p3 >= 90 AND p4 >= 9...,p6 >= 90 AND p7 >= 90 AND p8 >= 90 AND p9 >= 9...,12,p1 >= 60 AND p2 >= 60 AND p3 >= 60 AND p4 >= 6...,p10 >= 55 AND p16 >= 60 AND p6 >= 60 AND p7 >=...,0.104862,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
40,0.414297,diag_90,p1 >= 90 AND p2 >= 90 AND p3 >= 90 AND p4 >= 9...,p6 >= 90 AND p7 >= 90 AND p8 >= 90 AND p9 >= 9...,15,p1 >= 55 AND p13 >= 50 AND p2 >= 60 AND p3 >= ...,p10 >= 55 AND p16 >= 60 AND p7 >= 55 AND p8 >=...,0.107954,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
43,0.406149,diag_90,p1 >= 90 AND p2 >= 90 AND p3 >= 90 AND p4 >= 9...,p6 >= 90 AND p7 >= 90 AND p8 >= 90 AND p9 >= 9...,18,p1 >= 50 AND p19 >= 50 AND p3 >= 55 AND p4 >= ...,p10 >= 60 AND p18 >= 55 AND p6 >= 50 AND p7 >=...,0.118544,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
44,0.452809,diag_90,p1 >= 90 AND p2 >= 90 AND p3 >= 90 AND p4 >= 9...,p6 >= 90 AND p7 >= 90 AND p8 >= 90 AND p9 >= 9...,19,p1 > 40 AND p2 > 65 AND p3 >= 65 AND p4 > 50 A...,p10 > 45 AND p6 > 50 AND p7 >= 55 AND p8 <= 55...,0.086996,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
50,0.666667,diag_75,p1 >= 75 AND p2 >= 75 AND p3 >= 75 AND p4 >= 7...,p6 >= 75 AND p7 >= 75 AND p8 >= 75 AND p9 >= 7...,cand_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.097617,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
55,0.544615,diag_75,p1 >= 75 AND p2 >= 75 AND p3 >= 75 AND p4 >= 7...,p6 >= 75 AND p7 >= 75 AND p8 >= 75 AND p9 >= 7...,5,p1 >= 45 AND p2 < 65 AND p3 >= 55 AND p4 >= 40...,p10 < 45 AND p6 <= 50 AND p7 >= 40 AND p8 >= 4...,0.122727,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
56,0.712909,diag_75,p1 >= 75 AND p2 >= 75 AND p3 >= 75 AND p4 >= 7...,p6 >= 75 AND p7 >= 75 AND p8 >= 75 AND p9 >= 7...,6,p1 >= 55 AND p18 >= 55 AND p2 >= 60 AND p3 >= ...,p10 >= 60 AND p6 >= 60 AND p7 >= 55 AND p8 >= ...,0.117543,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
57,0.687909,diag_75,p1 >= 75 AND p2 >= 75 AND p3 >= 75 AND p4 >= 7...,p6 >= 75 AND p7 >= 75 AND p8 >= 75 AND p9 >= 7...,7,p1 >= 50 AND p2 >= 50 AND p20 >= 60 AND p3 >= ...,p10 >= 50 AND p6 >= 50 AND p7 >= 60 AND p8 >= ...,0.125832,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
62,0.717539,diag_75,p1 >= 75 AND p2 >= 75 AND p3 >= 75 AND p4 >= 7...,p6 >= 75 AND p7 >= 75 AND p8 >= 75 AND p9 >= 7...,12,p1 >= 60 AND p2 >= 60 AND p3 >= 60 AND p4 >= 6...,p10 >= 55 AND p16 >= 60 AND p6 >= 60 AND p7 >=...,0.095359,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
65,0.645549,diag_75,p1 >= 75 AND p2 >= 75 AND p3 >= 75 AND p4 >= 7...,p6 >= 75 AND p7 >= 75 AND p8 >= 75 AND p9 >= 7...,15,p1 >= 55 AND p13 >= 50 AND p2 >= 60 AND p3 >= ...,p10 >= 55 AND p16 >= 60 AND p7 >= 55 AND p8 >=...,0.161644,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
68,0.625178,diag_75,p1 >= 75 AND p2 >= 75 AND p3 >= 75 AND p4 >= 7...,p6 >= 75 AND p7 >= 75 AND p8 >= 75 AND p9 >= 7...,18,p1 >= 50 AND p19 >= 50 AND p3 >= 55 AND p4 >= ...,p10 >= 60 AND p18 >= 55 AND p6 >= 50 AND p7 >=...,0.115225,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
69,0.632024,diag_75,p1 >= 75 AND p2 >= 75 AND p3 >= 75 AND p4 >= 7...,p6 >= 75 AND p7 >= 75 AND p8 >= 75 AND p9 >= 7...,19,p1 > 40 AND p2 > 65 AND p3 >= 65 AND p4 > 50 A...,p10 > 45 AND p6 > 50 AND p7 >= 55 AND p8 <= 55...,0.093000,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
75,0.777780,diag_25,p1 >= 25 AND p2 >= 25 AND p3 >= 25 AND p4 >= 2...,p6 >= 25 AND p7 >= 25 AND p8 >= 25 AND p9 >= 2...,cand_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.110011,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
80,0.736666,diag_25,p1 >= 25 AND p2 >= 25 AND p3 >= 25 AND p4 >= 2...,p6 >= 25 AND p7 >= 25 AND p8 >= 25 AND p9 >= 2...,5,p1 >= 45 AND p2 < 65 AND p3 >= 55 AND p4 >= 40...,p10 < 45 AND p6 <= 50 AND p7 >= 40 AND p8 >= 4...,0.108965,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
81,0.713463,diag_25,p1 >= 25 AND p2 >= 25 AND p3 >= 25 AND p4 >= 2...,p6 >= 25 AND p7 >= 25 AND p8 >= 25 AND p9 >= 2...,6,p1 >= 55 AND p18 >= 55 AND p2 >= 60 AND p3 >= ...,p10 >= 60 AND p6 >= 60 AND p7 >= 55 AND p8 >= ...,0.131557,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
82,0.740131,diag_25,p1 >= 25 AND p2 >= 25 AND p3 >= 25 AND p4 >= 2...,p6 >= 25 AND p7 >= 25 AND p8 >= 25 AND p9 >= 2...,7,p1 >= 50 AND p2 >= 50 AND p20 >= 60 AND p3 >= ...,p10 >= 50 AND p6 >= 50 AND p7 >= 60 AND p8 >= ...,0.100333,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
87,0.709019,diag_25,p1 >= 25 AND p2 >= 25 AND p3 >= 25 AND p4 >= 2...,p6 >= 25 AND p7 >= 25 AND p8 >= 25 AND p9 >= 2...,12,p1 >= 60 AND p2 >= 60 AND p3 >= 60 AND p4 >= 6...,p10 >= 55 AND p16 >= 60 AND p6 >= 60 AND p7 >=...,0.130294,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
90,0.646797,diag_25,p1 >= 25 AND p2 >= 25 AND p3 >= 25 AND p4 >= 2...,p6 >= 25 AND p7 >= 25 AND p8 >= 25 AND p9 >= 2...,15,p1 >= 55 AND p13 >= 50 AND p2 >= 60 AND p3 >= ...,p10 >= 55 AND p16 >= 60 AND p7 >= 55 AND p8 >=...,0.110787,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
93,0.669020,diag_25,p1 >= 25 AND p2 >= 25 AND p3 >= 25 AND p4 >= 2...,p6 >= 25 AND p7 >= 25 AND p8 >= 25 AND p9 >= 2...,18,p1 >= 50 AND p19 >= 50 AND p3 >= 55 AND p4 >= ...,p10 >= 60 AND p18 >= 55 AND p6 >= 50 AND p7 >=...,0.107151,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
94,0.708889,diag_25,p1 >= 25 AND p2 >= 25 AND p3 >= 25 AND p4 >= 2...,p6 >= 25 AND p7 >= 25 AND p8 >= 25 AND p9 >= 2...,19,p1 > 40 AND p2 > 65 AND p3 >= 65 AND p4 > 50 A...,p10 > 45 AND p6 > 50 AND p7 >= 55 AND p8 <= 55...,0.096098,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
100,0.703707,diag_10,p1 >= 10 AND p2 >= 10 AND p3 >= 10 AND p4 >= 1...,p6 >= 10 AND p7 >= 10 AND p8 >= 10 AND p9 >= 1...,cand_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.128589,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
105,0.708889,diag_10,p1 >= 10 AND p2 >= 10 AND p3 >= 10 AND p4 >= 1...,p6 >= 10 AND p7 >= 10 AND p8 >= 10 AND p9 >= 1...,5,p1 >= 45 AND p2 < 65 AND p3 >= 55 AND p4 >= 40...,p10 < 45 AND p6 <= 50 AND p7 >= 40 AND p8 >= 4...,0.122086,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
106,0.649019,diag_10,p1 >= 10 AND p2 >= 10 AND p3 >= 10 AND p4 >= 1...,p6 >= 10 AND p7 >= 10 AND p8 >= 10 AND p9 >= 1...,6,p1 >= 55 AND p18 >= 55 AND p2 >= 60 AND p3 >= ...,p10 >= 60 AND p6 >= 60 AND p7 >= 55 AND p8 >= ...,0.118466,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
107,0.671243,diag_10,p1 >= 10 AND p2 >= 10 AND p3 >= 10 AND p4 >= 1...,p6 >= 10 AND p7 >= 10 AND p8 >= 10 AND p9 >= 1...,7,p1 >= 50 AND p2 >= 50 AND p20 >= 60 AND p3 >= ...,p10 >= 50 AND p6 >= 50 AND p7 >= 60 AND p8 >= ...,0.103320,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
112,0.645315,diag_10,p1 >= 10 AND p2 >= 10 AND p3 >= 10 AND p4 >= 1...,p6 >= 10 AND p7 >= 10 AND p8 >= 10 AND p9 >= 1...,12,p1 >= 60 AND p2 >= 60 AND p3 >= 60 AND p4 >= 6...,p10 >= 55 AND p16 >= 60 AND p6 >= 60 AND p7 >=...,0.104686,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
115,0.582352,diag_10,p1 >= 10 AND p2 >= 10 AND p3 >= 10 AND p4 >= 1...,p6 >= 10 AND p7 >= 10 AND p8 >= 10 AND p9 >= 1...,15,p1 >= 55 AND p13 >= 50 AND p2 >= 60 AND p3 >= ...,p10 >= 55 AND p16 >= 60 AND p7 >= 55 AND p8 >=...,0.099911,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
118,0.600872,diag_10,p1 >= 10 AND p2 >= 10 AND p3 >= 10 AND p4 >= 1...,p6 >= 10 AND p7 >= 10 AND p8 >= 10 AND p9 >= 1...,18,p1 >= 50 AND p19 >= 50 AND p3 >= 55 AND p4 >= ...,p10 >= 60 AND p18 >= 55 AND p6 >= 50 AND p7 >=...,0.096121,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
119,0.674075,diag_10,p1 >= 10 AND p2 >= 10 AND p3 >= 10 AND p4 >= 1...,p6 >= 10 AND p7 >= 10 AND p8 >= 10 AND p9 >= 1...,19,p1 > 40 AND p2 > 65 AND p3 >= 65 AND p4 > 50 A...,p10 > 45 AND p6 > 50 AND p7 >= 55 AND p8 <= 55...,0.102591,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."

In [4]:
mapping = {
    "6": 1,
    "7": 2,
    "12":  3,
    "15":  4,
    "18":  5,
    "19": 6,
    "5":  7,
    # "diagnosed_baseline" não entra no mapping para permanecer igual
}

# Garante comparação por string, aplica o mapeamento e preserva o que não estiver no dict
df['candidate_name'] = (
    df['candidate_name'].map(mapping)
                         .fillna(df['candidate_name'])
)

C:\Users\lucas_alves\AppData\Local\Temp\ipykernel_15604\24626586.py:13: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [5]:
df

,similarity_result,diagnosed_name,diagnosed_given,diagnosed_then,candidate_name,candidate_given,candidate_then,elapsed_time,config
0,1.000000,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,cand_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.105050,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
5,0.751817,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,7.0,p1 >= 45 AND p2 < 65 AND p3 >= 55 AND p4 >= 40...,p10 < 45 AND p6 <= 50 AND p7 >= 40 AND p8 >= 4...,0.109494,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
6,0.906797,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,1.0,p1 >= 55 AND p18 >= 55 AND p2 >= 60 AND p3 >= ...,p10 >= 60 AND p6 >= 60 AND p7 >= 55 AND p8 >= ...,0.136965,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
7,0.946797,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,2.0,p1 >= 50 AND p2 >= 50 AND p20 >= 60 AND p3 >= ...,p10 >= 50 AND p6 >= 50 AND p7 >= 60 AND p8 >= ...,0.111955,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
12,0.900131,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,3.0,p1 >= 60 AND p2 >= 60 AND p3 >= 60 AND p4 >= 6...,p10 >= 55 AND p16 >= 60 AND p6 >= 60 AND p7 >=...,0.112124,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
15,0.840131,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,4.0,p1 >= 55 AND p13 >= 50 AND p2 >= 60 AND p3 >= ...,p10 >= 55 AND p16 >= 60 AND p7 >= 55 AND p8 >=...,0.180782,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
18,0.873464,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,5.0,p1 >= 50 AND p19 >= 50 AND p3 >= 55 AND p4 >= ...,p10 >= 60 AND p18 >= 55 AND p6 >= 50 AND p7 >=...,0.152935,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
19,0.802828,diag_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,6.0,p1 > 40 AND p2 > 65 AND p3 >= 65 AND p4 > 50 A...,p10 > 45 AND p6 > 50 AND p7 >= 55 AND p8 <= 55...,0.131406,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
25,0.466667,diag_90,p1 >= 90 AND p2 >= 90 AND p3 >= 90 AND p4 >= 9...,p6 >= 90 AND p7 >= 90 AND p8 >= 90 AND p9 >= 9...,cand_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.120358,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
30,0.417846,diag_90,p1 >= 90 AND p2 >= 90 AND p3 >= 90 AND p4 >= 9...,p6 >= 90 AND p7 >= 90 AND p8 >= 90 AND p9 >= 9...,7.0,p1 >= 45 AND p2 < 65 AND p3 >= 55 AND p4 >= 40...,p10 < 45 AND p6 <= 50 AND p7 >= 40 AND p8 >= 4...,0.102087,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
31,0.481241,diag_90,p1 >= 90 AND p2 >= 90 AND p3 >= 90 AND p4 >= 9...,p6 >= 90 AND p7 >= 90 AND p8 >= 90 AND p9 >= 9...,1.0,p1 >= 55 AND p18 >= 55 AND p2 >= 60 AND p3 >= ...,p10 >= 60 AND p6 >= 60 AND p7 >= 55 AND p8 >= ...,0.091496,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
32,0.471241,diag_90,p1 >= 90 AND p2 >= 90 AND p3 >= 90 AND p4 >= 9...,p6 >= 90 AND p7 >= 90 AND p8 >= 90 AND p9 >= 9...,2.0,p1 >= 50 AND p2 >= 50 AND p20 >= 60 AND p3 >= ...,p10 >= 50 AND p6 >= 50 AND p7 >= 60 AND p8 >= ...,0.132202,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
37,0.483093,diag_90,p1 >= 90 AND p2 >= 90 AND p3 >= 90 AND p4 >= 9...,p6 >= 90 AND p7 >= 90 AND p8 >= 90 AND p9 >= 9...,3.0,p1 >= 60 AND p2 >= 60 AND p3 >= 60 AND p4 >= 6...,p10 >= 55 AND p16 >= 60 AND p6 >= 60 AND p7 >=...,0.104862,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
40,0.414297,diag_90,p1 >= 90 AND p2 >= 90 AND p3 >= 90 AND p4 >= 9...,p6 >= 90 AND p7 >= 90 AND p8 >= 90 AND p9 >= 9...,4.0,p1 >= 55 AND p13 >= 50 AND p2 >= 60 AND p3 >= ...,p10 >= 55 AND p16 >= 60 AND p7 >= 55 AND p8 >=...,0.107954,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
43,0.406149,diag_90,p1 >= 90 AND p2 >= 90 AND p3 >= 90 AND p4 >= 9...,p6 >= 90 AND p7 >= 90 AND p8 >= 90 AND p9 >= 9...,5.0,p1 >= 50 AND p19 >= 50 AND p3 >= 55 AND p4 >= ...,p10 >= 60 AND p18 >= 55 AND p6 >= 50 AND p7 >=...,0.118544,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
44,0.452809,diag_90,p1 >= 90 AND p2 >= 90 AND p3 >= 90 AND p4 >= 9...,p6 >= 90 AND p7 >= 90 AND p8 >= 90 AND p9 >= 9...,6.0,p1 > 40 AND p2 > 65 AND p3 >= 65 AND p4 > 50 A...,p10 > 45 AND p6 > 50 AND p7 >= 55 AND p8 <= 55...,0.086996,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
50,0.666667,diag_75,p1 >= 75 AND p2 >= 75 AND p3 >= 75 AND p4 >= 7...,p6 >= 75 AND p7 >= 75 AND p8 >= 75 AND p9 >= 7...,cand_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.097617,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
55,0.544615,diag_75,p1 >= 75 AND p2 >= 75 AND p3 >= 75 AND p4 >= 7...,p6 >= 75 AND p7 >= 75 AND p8 >= 75 AND p9 >= 7...,7.0,p1 >= 45 AND p2 < 65 AND p3 >= 55 AND p4 >= 40...,p10 < 45 AND p6 <= 50 AND p7 >= 40 AND p8 >= 4...,0.122727,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
56,0.712909,diag_75,p1 >= 75 AND p2 >= 75 AND p3 >= 75 AND p4 >= 7...,p6 >= 75 AND p7 >= 75 AND p8 >= 75 AND p9 >= 7...,1.0,p1 >= 55 AND p18 >= 55 AND p2 >= 60 AND p3 >= ...,p10 >= 60 AND p6 >= 60 AND p7 >= 55 AND p8 >= ...,0.117543,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
57,0.687909,diag_75,p1 >= 75 AND p2 >= 75 AND p3 >= 75 AND p4 >= 7...,p6 >= 75 AND p7 >= 75 AND p8 >= 75 AND p9 >= 7...,2.0,p1 >= 50 AND p2 >= 50 AND p20 >= 60 AND p3 >= ...,p10 >= 50 AND p6 >= 50 AND p7 >= 60 AND p8 >= ...,0.125832,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
62,0.717539,diag_75,p1 >= 75 AND p2 >= 75 AND p3 >= 75 AND p4 >= 7...,p6 >= 75 AND p7 >= 75 AND p8 >= 75 AND p9 >= 7...,3.0,p1 >= 60 AND p2 >= 60 AND p3 >= 60 AND p4 >= 6...,p10 >= 55 AND p16 >= 60 AND p6 >= 60 AND p7 >=...,0.095359,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
65,0.645549,diag_75,p1 >= 75 AND p2 >= 75 AND p3 >= 75 AND p4 >= 7...,p6 >= 75 AND p7 >= 75 AND p8 >= 75 AND p9 >= 7...,4.0,p1 >= 55 AND p13 >= 50 AND p2 >= 60 AND p3 >= ...,p10 >= 55 AND p16 >= 60 AND p7 >= 55 AND p8 >=...,0.161644,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
68,0.625178,diag_75,p1 >= 75 AND p2 >= 75 AND p3 >= 75 AND p4 >= 7...,p6 >= 75 AND p7 >= 75 AND p8 >= 75 AND p9 >= 7...,5.0,p1 >= 50 AND p19 >= 50 AND p3 >= 55 AND p4 >= ...,p10 >= 60 AND p18 >= 55 AND p6 >= 50 AND p7 >=...,0.115225,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
69,0.632024,diag_75,p1 >= 75 AND p2 >= 75 AND p3 >= 75 AND p4 >= 7...,p6 >= 75 AND p7 >= 75 AND p8 >= 75 AND p9 >= 7...,6.0,p1 > 40 AND p2 > 65 AND p3 >= 65 AND p4 > 50 A...,p10 > 45 AND p6 > 50 AND p7 >= 55 AND p8 <= 55...,0.093000,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
75,0.777780,diag_25,p1 >= 25 AND p2 >= 25 AND p3 >= 25 AND p4 >= 2...,p6 >= 25 AND p7 >= 25 AND p8 >= 25 AND p9 >= 2...,cand_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.110011,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
80,0.736666,diag_25,p1 >= 25 AND p2 >= 25 AND p3 >= 25 AND p4 >= 2...,p6 >= 25 AND p7 >= 25 AND p8 >= 25 AND p9 >= 2...,7.0,p1 >= 45 AND p2 < 65 AND p3 >= 55 AND p4 >= 40...,p10 < 45 AND p6 <= 50 AND p7 >= 40 AND p8 >= 4...,0.108965,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
81,0.713463,diag_25,p1 >= 25 AND p2 >= 25 AND p3 >= 25 AND p4 >= 2...,p6 >= 25 AND p7 >= 25 AND p8 >= 25 AND p9 >= 2...,1.0,p1 >= 55 AND p18 >= 55 AND p2 >= 60 AND p3 >= ...,p10 >= 60 AND p6 >= 60 AND p7 >= 55 AND p8 >= ...,0.131557,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
82,0.740131,diag_25,p1 >= 25 AND p2 >= 25 AND p3 >= 25 AND p4 >= 2...,p6 >= 25 AND p7 >= 25 AND p8 >= 25 AND p9 >= 2...,2.0,p1 >= 50 AND p2 >= 50 AND p20 >= 60 AND p3 >= ...,p10 >= 50 AND p6 >= 50 AND p7 >= 60 AND p8 >= ...,0.100333,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
87,0.709019,diag_25,p1 >= 25 AND p2 >= 25 AND p3 >= 25 AND p4 >= 2...,p6 >= 25 AND p7 >= 25 AND p8 >= 25 AND p9 >= 2...,3.0,p1 >= 60 AND p2 >= 60 AND p3 >= 60 AND p4 >= 6...,p10 >= 55 AND p16 >= 60 AND p6 >= 60 AND p7 >=...,0.130294,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
90,0.646797,diag_25,p1 >= 25 AND p2 >= 25 AND p3 >= 25 AND p4 >= 2...,p6 >= 25 AND p7 >= 25 AND p8 >= 25 AND p9 >= 2...,4.0,p1 >= 55 AND p13 >= 50 AND p2 >= 60 AND p3 >= ...,p10 >= 55 AND p16 >= 60 AND p7 >= 55 AND p8 >=...,0.110787,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
93,0.669020,diag_25,p1 >= 25 AND p2 >= 25 AND p3 >= 25 AND p4 >= 2...,p6 >= 25 AND p7 >= 25 AND p8 >= 25 AND p9 >= 2...,5.0,p1 >= 50 AND p19 >= 50 AND p3 >= 55 AND p4 >= ...,p10 >= 60 AND p18 >= 55 AND p6 >= 50 AND p7 >=...,0.107151,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
94,0.708889,diag_25,p1 >= 25 AND p2 >= 25 AND p3 >= 25 AND p4 >= 2...,p6 >= 25 AND p7 >= 25 AND p8 >= 25 AND p9 >= 2...,6.0,p1 > 40 AND p2 > 65 AND p3 >= 65 AND p4 > 50 A...,p10 > 45 AND p6 > 50 AND p7 >= 55 AND p8 <= 55...,0.096098,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
100,0.703707,diag_10,p1 >= 10 AND p2 >= 10 AND p3 >= 10 AND p4 >= 1...,p6 >= 10 AND p7 >= 10 AND p8 >= 10 AND p9 >= 1...,cand_baseline,p1 >= 50 AND p2 >= 50 AND p3 >= 50 AND p4 >= 5...,p6 >= 50 AND p7 >= 50 AND p8 >= 50 AND p9 >= 5...,0.128589,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
105,0.708889,diag_10,p1 >= 10 AND p2 >= 10 AND p3 >= 10 AND p4 >= 1...,p6 >= 10 AND p7 >= 10 AND p8 >= 10 AND p9 >= 1...,7.0,p1 >= 45 AND p2 < 65 AND p3 >= 55 AND p4 >= 40...,p10 < 45 AND p6 <= 50 AND p7 >= 40 AND p8 >= 4...,0.122086,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
106,0.649019,diag_10,p1 >= 10 AND p2 >= 10 AND p3 >= 10 AND p4 >= 1...,p6 >= 10 AND p7 >= 10 AND p8 >= 10 AND p9 >= 1...,1.0,p1 >= 55 AND p18 >= 55 AND p2 >= 60 AND p3 >= ...,p10 >= 60 AND p6 >= 60 AND p7 >= 55 AND p8 >= ...,0.118466,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
107,0.671243,diag_10,p1 >= 10 AND p2 >= 10 AND p3 >= 10 AND p4 >= 1...,p6 >= 10 AND p7 >= 10 AND p8 >= 10 AND p9 >= 1...,2.0,p1 >= 50 AND p2 >= 50 AND p20 >= 60 AND p3 >= ...,p10 >= 50 AND p6 >= 50 AND p7 >= 60 AND p8 >= ...,0.103320,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
112,0.645315,diag_10,p1 >= 10 AND p2 >= 10 AND p3 >= 10 AND p4 >= 1...,p6 >= 10 AND p7 >= 10 AND p8 >= 10 AND p9 >= 1...,3.0,p1 >= 60 AND p2 >= 60 AND p3 >= 60 AND p4 >= 6...,p10 >= 55 AND p16 >= 60 AND p6 >= 60 AND p7 >=...,0.104686,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
115,0.582352,diag_10,p1 >= 10 AND p2 >= 10 AND p3 >= 10 AND p4 >= 1...,p6 >= 10 AND p7 >= 10 AND p8 >= 10 AND p9 >= 1...,4.0,p1 >= 55 AND p13 >= 50 AND p2 >= 60 AND p3 >= ...,p10 >= 55 AND p16 >= 60 AND p7 >= 55 AND p8 >=...,0.099911,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
118,0.600872,diag_10,p1 >= 10 AND p2 >= 10 AND p3 >= 10 AND p4 >= 1...,p6 >= 10 AND p7 >= 10 AND p8 >= 10 AND p9 >= 1...,5.0,p1 >= 50 AND p19 >= 50 AND p3 >= 55 AND p4 >= ...,p10 >= 60 AND p18 >= 55 AND p6 >= 50 AND p7 >=...,0.096121,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."
119,0.674075,diag_10,p1 >= 10 AND p2 >= 10 AND p3 >= 10 AND p4 >= 1...,p6 >= 10 AND p7 >= 10 AND p8 >= 10 AND p9 >= 1...,6.0,p1 > 40 AND p2 > 65 AND p3 >= 65 AND p4 > 50 A...,p10 > 45 AND p6 > 50 AND p7 >= 55 AND p8 <= 55...,0.102591,"{'parameter_weights': {'parameter_1': 1.0, 'pa..."

In [10]:
import pandas as pd
import plotly.graph_objects as go

diagnosis_order = [
    "diag_90", "diag_75",
    "diag_baseline", 
    "diag_25", "diag_10"
]

# Supondo que seu DataFrame df já está filtrado para os candidatos desejados!
df_pivot = df.pivot(index="candidate_name", columns="diagnosed_name", values="similarity_result")
df_pivot = df_pivot[[col for col in diagnosis_order if col in df_pivot.columns]]
df_rank = df_pivot.rank(ascending=False, axis=0, method='min')

fig = go.Figure()

for cand in df_rank.index:
    similarity_texts = [f"{df_pivot.loc[cand, col]:.2f}" for col in df_pivot.columns]
    fig.add_trace(go.Scatter(
        x=df_rank.columns,
        y=df_rank.loc[cand],
        mode='lines+markers+text',
        name=str(cand),
        line=dict(width=4),
        marker=dict(size=13),
        text=similarity_texts,
        textposition="top center",
        textfont=dict(size=10)
    ))

# Linhas verticais tracejadas finas ao redor do diag_baseline
baseline_idx = diagnosis_order.index("diag_baseline")
fig.add_vline(
    x=baseline_idx - 0.48,
    line_width=1,
    line_dash="dash",
    line_color="black",
    opacity=0.5,
    layer='above'
)
fig.add_vline(
    x=baseline_idx + 0.48,
    line_width=1,
    line_dash="dash",
    line_color="black",
    opacity=0.5,
    layer='above'
)

fig.update_layout(
    title='Bump Chart - Ranking dos Candidatos ao Longo das Execuções',
    # xaxis_title='Execução Diagnóstica',
    # yaxis_title='Ranking (1 = topo)',
    yaxis=dict(autorange='reversed', dtick=1),
    xaxis=dict(
        tickangle=-45,
        categoryorder='array',
        categoryarray=diagnosis_order,
        tickvals=diagnosis_order,
        ticktext=diagnosis_order
    ),
    width=1000,
    height=700,
    legend=dict(
        title="Candidatos",
        orientation="h",          # legenda horizontal
        xanchor="center", x=0.5,  # centraliza
        yanchor="top",    y=-0.20,# posiciona abaixo do eixo X
        bgcolor="rgba(255,255,255,0.95)",
        bordercolor="#ccc",
        borderwidth=1,
        font=dict(size=13)
    ),
    margin=dict(l=40, r=40, t=70, b=160)  # margem inferior maior p/ legenda
)

fig.show()